<#
.SYNOPSIS
  KAEDE — Windows installer. Run via: iwr -Uri https://kaede.sh/install.ps1 | iex
.DESCRIPTION
  Installs KAEDE globally: clones repo, builds MCP server, links npm binary.
  Supports -Update and -Uninstall switches.
.PARAMETER Update
  Pull latest changes and rebuild.
.PARAMETER Uninstall
  Remove KAEDE and unlink global binary.
#>

param(
  [switch]$Update,
  [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'
$Repo = 'https://github.com/konxc/kaede-powerup'
$InstallDir = if ($env:KAEDE_DIR) { $env:KAEDE_DIR } else { "$HOME\.kaede" }
$ConfigDir = "$HOME\.config\kaede"

function Write-Logo {
  Write-Host ""
  Write-Host "╔══════════════════════════════════════╗" -ForegroundColor Magenta
  Write-Host "║         KAEDE — Installer            ║" -ForegroundColor Magenta
  Write-Host "╚══════════════════════════════════════╝" -ForegroundColor Magenta
  Write-Host ""
}

function Write-Info  { Write-Host "  $($args[0])" -ForegroundColor Cyan }
function Write-Ok    { Write-Host "  ✓ $($args[0])" -ForegroundColor Green }
function Write-Warn  { Write-Host "  ⚠  $($args[0])" -ForegroundColor Yellow }
function Write-Fail  { Write-Host "  ✗ $($args[0])" -ForegroundColor Red; exit 1 }

function Check-Prereqs {
  Write-Info "Checking prerequisites..."

  try {
    $nodeVer = node --version
    Write-Ok "Node.js $nodeVer"
  } catch {
    Write-Fail "Node.js not found. Install from https://nodejs.org (v18+)"
  }

  try {
    $bunVer = bun --version
    $script:HasBun = $true
    Write-Ok "Bun $bunVer"
  } catch {
    $script:HasBun = $false
    Write-Warn "Bun not found — MCP build will need manual step"
  }

  try {
    $gitVer = git --version
    Write-Ok $gitVer
  } catch {
    Write-Fail "Git not found. Install from https://git-scm.com"
  }

  # Check elevated (for npm link -g)
  $script:IsElevated = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
  if (-not $script:IsElevated) {
    Write-Warn "Not running as Administrator — npm link may fail"
    Write-Warn "Run PowerShell as Admin for full install, or use KAEDE_DIR manually"
  }
}

function CloneOrUpdate {
  if (Test-Path "$InstallDir\.git") {
    Write-Info "KAEDE already installed at $InstallDir"
    if ($Update) {
      Write-Info "Updating..."
      Push-Location $InstallDir
      git pull --rebase
      Pop-Location
      Write-Ok "Updated to latest"
    } else {
      Write-Ok "Already up to date. Use -Update to pull latest"
      exit 0
    }
  } else {
    Write-Info "Installing to $InstallDir ..."
    $parent = Split-Path $InstallDir -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    git clone --depth 1 $Repo $InstallDir 2>$null
    if (-not $?) { Write-Fail "Clone failed" }
    Write-Ok "Cloned kaede-powerup"
  }
}

function Install-Deps {
  Write-Info "Installing npm dependencies..."
  Push-Location $InstallDir
  npm install --silent 2>&1 | Out-Null
  if (-not $?) { Write-Fail "npm install failed" }
  Pop-Location
  Write-Ok "Dependencies installed"
}

function Build-Mcp {
  Write-Info "Building MCP server..."
  Push-Location $InstallDir
  if ($script:HasBun) {
    $result = bun build --target bun src/mcp-server.js --outfile dist/mcp-server.js 2>&1
    if ($LASTEXITCODE -eq 0) {
      Write-Ok "MCP server built with bun"
    } else {
      Write-Warn "MCP build failed: $result"
    }
  } else {
    Write-Warn "Skipping MCP build (bun required). Run manually: cd ~\.kaede && bun build..."
  }
  Pop-Location
}

function Link-Global {
  Write-Info "Linking globally..."
  Push-Location $InstallDir
  if ($script:IsElevated) {
    npm link 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Ok "KAEDE linked globally (try: kaede --help)"
    } else {
      Write-Warn "npm link failed. Try: cd $InstallDir && npm link"
    }
  } else {
    Write-Warn "Skipping npm link (not admin). Run manually: cd $InstallDir && npm link"
  }
  Pop-Location
}

function Setup-Config {
  if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
  }
  $secretsFile = "$ConfigDir\secrets.env"
  if (-not (Test-Path $secretsFile)) {
@"
# Trello API Credentials — generated by KAEDE installer
# Run 'kaede setup' or manually fill in:
# TRELLO_API_KEY=your-key
# TRELLO_TOKEN=your-token
"@ | Out-File -FilePath $secretsFile -Encoding utf8
    Write-Ok "Created $secretsFile"
  }
}

function Write-NextSteps {
  Write-Host ""
  Write-Host "  ✅  KAEDE installed!" -ForegroundColor Green
  Write-Host ""
  Write-Host "  Next steps:" -ForegroundColor DarkGray
  Write-Host "    kaede setup            add Trello API credentials" -ForegroundColor DarkGray
  Write-Host "    kaede init <project>   setup project for MCP" -ForegroundColor DarkGray
  Write-Host "    kaede status --mcp     verify MCP connection" -ForegroundColor DarkGray
  Write-Host "    kaede today            view your cards" -ForegroundColor DarkGray
  Write-Host ""
  Write-Host "  Environment:" -ForegroundColor DarkGray
  Write-Host "    KAEDE_DIR=$InstallDir" -ForegroundColor DarkGray
  Write-Host "    $ConfigDir\secrets.env" -ForegroundColor DarkGray
  Write-Host ""
}

function Uninstall-KAEDE {
  $kaedeBin = Get-Command kaede -ErrorAction SilentlyContinue
  if ($kaedeBin) {
    Write-Info "Unlinking global binary..."
    Push-Location $InstallDir 2>$null
    npm unlink 2>$null
    Pop-Location
  }
  if (Test-Path $InstallDir) {
    Write-Info "Removing $InstallDir ..."
    Remove-Item -Recurse -Force $InstallDir
    Write-Ok "Removed $InstallDir"
  }
  if (Test-Path $ConfigDir) {
    Write-Host ""
    Write-Warn "Config directory preserved: $ConfigDir"
    Write-Host "  Remove manually: Remove-Item -Recurse -Force $ConfigDir" -ForegroundColor DarkGray
  }
  Write-Host ""
  Write-Host "  ✅  KAEDE uninstalled" -ForegroundColor Green
  Write-Host ""
}

# ─── Main ───

Write-Logo

if ($Uninstall) {
  Uninstall-KAEDE
} elseif ($Update) {
  Check-Prereqs
  CloneOrUpdate
  Install-Deps
  Build-Mcp
  Write-Host ""
  Write-Ok "KAEDE updated to latest"
} else {
  Check-Prereqs
  CloneOrUpdate
  Install-Deps
  Build-Mcp
  Link-Global
  Setup-Config
  Write-NextSteps
}
