#!/usr/bin/env bun
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { homedir } from 'os';
import { createInterface } from 'readline';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KAEDE_DIR = process.env.KAEDE_DIR ? resolve(process.env.KAEDE_DIR) : resolve(__dirname, '..');
const KAEDE_GLOBAL_DIR = resolve(homedir(), '.kaede');

interface EnvVars {
  TRELLO_API_KEY?: string;
  TRELLO_TOKEN?: string;
  [key: string]: string | undefined;
}

function loadEnv(filePath: string): EnvVars {
  if (!existsSync(filePath)) return {};
  const content = readFileSync(filePath, 'utf-8');
  const vars: EnvVars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) vars[key] = val;
  }
  return vars;
}

function getSecrets(): EnvVars {
  const global = resolve(homedir(), '.config', 'kaede', 'secrets.env');
  const local = resolve(process.cwd(), 'secrets.env');
  const dev = resolve(KAEDE_DIR, 'secrets.env');

  let merged: EnvVars = {};
  for (const p of [dev, local, global]) {
    merged = { ...merged, ...loadEnv(p) };
  }
  return merged;
}

let readline = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(query: string): Promise<string> {
  return new Promise((resolveFn) => readline.question(query, resolveFn));
}

// ─── Commands ───

async function cmdSetup(): Promise<void> {
  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Setup Wizard          ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const existing = getSecrets();
  if (existing.TRELLO_API_KEY) {
    console.log(`  \x1b[33m⚠  Credentials already configured\x1b[0m`);
    console.log(`  \x1b[33m   API Key: ${existing.TRELLO_API_KEY.slice(0, 8)}...\x1b[0m`);
    const wants = await ask('  \x1b[36m  Overwrite? (y/N): \x1b[0m');
    if (wants.toLowerCase() !== 'y') {
      console.log('  \x1b[32m  OK, keeping existing credentials.\x1b[0m');
      readline.close();
      return;
    }
  }

  console.log('  \x1b[90m  ──────────────────────────────────────\x1b[0m');
  console.log('  \x1b[90m  To get Trello API credentials:\x1b[0m');
  console.log('  \x1b[90m  1. Go to https://trello.com/power-ups/admin\x1b[0m');
  console.log('  \x1b[90m  2. Create a Power-Up or use existing\x1b[0m');
  console.log('  \x1b[90m  3. Copy API Key and generate a Token\x1b[0m');
  console.log('  \x1b[90m  ──────────────────────────────────────\x1b[0m');
  console.log('');

  const apiKey = await ask('  \x1b[36m  Trello API Key: \x1b[0m');
  if (!apiKey.trim()) {
    console.log('  \x1b[31m  ✗ API Key required.\x1b[0m');
    readline.close();
    return;
  }

  const token = await ask('  \x1b[36m  Trello Token: \x1b[0m');
  if (!token.trim()) {
    console.log('  \x1b[31m  ✗ Token required.\x1b[0m');
    readline.close();
    return;
  }

  const envContent = [
    '# Trello API Credentials — generated by `kaede setup`',
    '# Keep this file secret! Do NOT commit to git.',
    '',
    `TRELLO_API_KEY=${apiKey.trim()}`,
    `TRELLO_TOKEN=${token.trim()}`,
    '',
  ].join('\n');

  const configDir = resolve(homedir(), '.config', 'kaede');
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }
  const globalPath = resolve(configDir, 'secrets.env');
  writeFileSync(globalPath, envContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Saved to ${globalPath} (global config)\x1b[0m`);

  console.log('');
  console.log('  \x1b[32m  ✅  KAEDE credentials configured!\x1b[0m');
  console.log('  \x1b[90m     You can now run: kaede today\x1b[0m');
  console.log('');
  readline.close();
}

async function cmdToday(): Promise<void> {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  \u2717 Trello credentials not found.\x1b[0m');
    console.error('  \x1b[33m  Run `bun scripts/kaede.ts setup` first.\x1b[0m');
    return;
  }

  const apiBase = 'https://api.trello.com/1';
  const auth = `key=${secrets.TRELLO_API_KEY}&token=${secrets.TRELLO_TOKEN}`;

  try {
    const meRes = await fetch(`${apiBase}/members/me?${auth}`);
    const me = await meRes.json() as { id: string; fullName?: string; username?: string };

    const boardsRes = await fetch(`${apiBase}/members/${me.id}/boards?${auth}&fields=name,id,url,closed&filter=open`);
    const boards = await boardsRes.json() as Array<Record<string, unknown>>;

    console.log('');
    console.log(`  \x1b[35m╔══════════════════════════════════════╗\x1b[0m`);
    console.log(`  \x1b[35m║      KAEDE — Today's Tasks           ║\x1b[0m`);
    console.log(`  \x1b[35m╚══════════════════════════════════════╝\x1b[0m`);
    console.log(
      `  \x1b[90m  ${me.fullName || me.username} · ${new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\x1b[0m`,
    );
    console.log('');

    let hasTasks = false;

    for (const board of boards) {
      const listsRes = await fetch(`${apiBase}/boards/${board.id}/lists?${auth}&fields=name,id`);
      const lists = await listsRes.json() as Array<Record<string, unknown>>;

      for (const list of lists) {
        const cardsRes = await fetch(
          `${apiBase}/lists/${list.id}/cards?${auth}&fields=name,id,due,dueComplete,idMembers,url,desc,dateLastActivity&members=true`,
        );
        const cards = await cardsRes.json() as Array<{ idMembers?: string[]; name: string; due?: string; dueComplete?: boolean; desc?: string }>;

        const myCards = cards.filter((c) => c.idMembers && c.idMembers.includes(me.id));

        if (myCards.length === 0) continue;
        hasTasks = true;

        console.log(`  \x1b[36m  ${board.name as string}\x1b[0m \x1b[90m→\x1b[0m \x1b[33m${list.name as string}\x1b[0m`);
        console.log(`  \x1b[90m  ${'─'.repeat(Math.max((board.name as string).length + (list.name as string).length + 4, 20))}\x1b[0m`);

        for (const card of myCards) {
          const due = card.due
            ? new Date(card.due).toLocaleDateString('id-ID', {
                day: 'numeric',
                month: 'short',
              })
            : '';
          const isOverdue = card.due && new Date(card.due) < new Date() && !card.dueComplete;
          const dueStr = due
            ? ` \x1b[90m[\x1b[0m${isOverdue ? '\x1b[31m⚠ ' : '\x1b[32m'}` +
              `${due}\x1b[0m${card.dueComplete ? ' ✓' : ''}\x1b[90m]\x1b[0m`
            : '';

          console.log(`    \x1b[37m• ${card.name}\x1b[0m${dueStr}`);
          if (card.desc) {
            const firstLine = card.desc.split('\n')[0].slice(0, 80);
            console.log(`     \x1b[90m${firstLine}\x1b[0m`);
          }
        }
        console.log('');
      }
    }

    if (!hasTasks) {
      console.log('  \x1b[90m  No tasks assigned to you. Enjoy your day! 🎉\x1b[0m');
      console.log('');
    }
  } catch (err) {
    console.error('  \x1b[31m  ✗ Failed to fetch Trello data:\x1b[0m', (err as Error).message);
  }
}

async function cmdInit(): Promise<void> {
  // Parse args: [dir] [--name X] [--tech X] [--db X]
  const args = process.argv.slice(3);
  const targetDir = resolve(args.find((_, i, a) => !a[i].startsWith('-')) || process.cwd());
  const getOpt = (flag: string) => {
    const i = args.indexOf(flag);
    return i !== -1 ? args[i + 1] : undefined;
  };
  const isInteractive = args.length === 0 || args[0] === '.' || !args[0].startsWith('-');
  const projectName = getOpt('--name') || '';
  const techStack = getOpt('--tech') || '';
  const dbType = getOpt('--db') || '';
  const playbookRef = getOpt('--playbook') || '';

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Init Project          ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  // 1. Check credentials
  const secrets = getSecrets();
  const hasCreds = !!(secrets.TRELLO_API_KEY && secrets.TRELLO_TOKEN);
  if (!hasCreds && isInteractive) {
    console.log('  \x1b[33m  ⚠  Trello credentials not configured.\x1b[0m');
    console.log('  \x1b[33m     Run `kaede setup` later.\x1b[0m');
    console.log('');
  }

  // 2. Create .opencode directory
  const opencodeDir = resolve(targetDir, '.opencode');
  const sharedDir = resolve(opencodeDir, 'SHARED');
  mkdirSync(sharedDir, { recursive: true });

  // 3. Write opencode.json
  const config = {
    agent: {
      name: projectName || targetDir.split(/[\\/]/).pop() || 'my-project',
      version: '1.0.0',
    },
    mcp: {
      trello: {
        type: 'local',
        command: ['bun', resolve(KAEDE_DIR, 'dist', 'mcp-server.js')],
        enabled: true,
        timeout: 30000,
      },
      kaede: {
        type: 'local',
        command: ['bun', resolve(KAEDE_DIR, 'dist', 'kaede-mcp-server.js')],
        enabled: true,
        timeout: 60000,
      },
    },
  };
  writeFileSync(resolve(opencodeDir, 'opencode.json'), JSON.stringify(config, null, 2) + '\n', 'utf-8');
  console.log(`  \x1b[32m  ✓ Created \x1b[0m${resolve(opencodeDir, 'opencode.json')}`);

  // 4. Write project-context.md
  const contextContent = [
    `# ${projectName || 'Project'} — KAEDE Environment`,
    '',
    techStack ? `- **Tech Stack:** ${techStack}` : null,
    dbType ? `- **Database:** ${dbType}` : null,
    playbookRef ? `- **Playbook:** \`${playbookRef}\`` : null,
    '',
    '## MCP Servers',
    '',
    'This project uses two MCP servers managed by KAEDE:',
    '',
    '| Server | Description |',
    '|--------|-------------|',
    '| `mcp.trello` | 42 Trello API tools (cards, boards, lists, labels, checklists, etc.)',
    '| `mcp.kaede` | 4 orchestration tools (playbook parse, context bundle, plan generation, status)',
    '',
    '## Workflow',
    '',
    '```',
    '1. Write intent in natural language',
    '2. mcp.kaede.generate_plan() → action steps',
    '3. mcp.trello.<tool>() → execute each step',
    '```',
    '',
  ]
    .filter(Boolean)
    .join('\n');
  writeFileSync(resolve(sharedDir, 'project-context.md'), contextContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Created \x1b[0m${resolve(sharedDir, 'project-context.md')}`);

  // 5. Write basic agent-rules.md
  const rulesContent = [
    '## Agent Rules',
    '',
    '### Communication',
    '- Default bahasa Indonesia untuk komunikasi internal tim',
    '- Gunakan English untuk dokumentasi teknis dan kode',
    '',
    '### Workflow',
    '- Selalu gunakan `mcp.kaede.generate_plan()` dulu untuk task besar',
    '- Eksekusi step-by-step via `mcp.trello` tools',
    '- Untuk task sederhana, langsung gunakan `mcp.trello` tools',
    '',
  ].join('\n');
  writeFileSync(resolve(sharedDir, 'agent-rules.md'), rulesContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Created \x1b[0m${resolve(sharedDir, 'agent-rules.md')}`);

  console.log('');
  console.log('  \x1b[32m  ✅  Project initialized with KAEDE.\x1b[0m');
  console.log('');
  console.log('  \x1b[90m     Next steps:\x1b[0m');
  console.log('  \x1b[90m       1. \x1b[36mkaede setup\x1b[0m    — configure Trello API credentials');
  console.log('  \x1b[90m       2. \x1b[36mkaede status\x1b[0m   — verify configuration');
  console.log('  \x1b[90m       3. \x1b[36mkaede today\x1b[0m    — view your tasks');
  console.log('');
}

// ── Push ──

interface TaskCard {
  title: string;
  desc?: string;
  labels?: string[];
  member?: string;
}

async function cmdPush(): Promise<void> {
  const args = process.argv.slice(3);
  const filePath = args.find((a) => !a.startsWith('-'));
  let boardName = '';
  let listName = '';
  let defaultLabels: string[] = [];

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--board') boardName = args[i + 1] || '';
    if (args[i] === '--list') listName = args[i + 1] || '';
    if (args[i] === '--labels') defaultLabels = (args[i + 1] || '').split(',').map((s: string) => s.trim());
  }

  if (!filePath) {
    console.error('  \x1b[31m  ✗ Usage: kaede push <file.md> [--board "Board Name"] [--list "List Name"]\x1b[0m');
    return;
  }

  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  \u2717 Trello credentials not found. Run `kaede setup` first.\x1b[0m');
    return;
  }

  const auth = `key=${secrets.TRELLO_API_KEY}&token=${secrets.TRELLO_TOKEN}`;
  const api = 'https://api.trello.com/1';

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Push Cards            ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  // Parse markdown → task cards
  const content = readFileSync(filePath, 'utf-8');
  const cards: TaskCard[] = [];
  let currentCard: TaskCard | null = null;

  for (const line of content.split('\n')) {
    const taskMatch = line.match(/^##\s+(.+)/);
    const descMatch = line.match(/^[-*]\s+(.+)/);
    const labelMatch = line.match(/^labels?:\s*(.+)/i);

    if (taskMatch) {
      if (currentCard) cards.push(currentCard);
      currentCard = { title: taskMatch[1].trim() };
    } else if (currentCard && descMatch) {
      currentCard.desc = (currentCard.desc ? currentCard.desc + '\n' : '') + descMatch[1].trim();
    } else if (currentCard && labelMatch) {
      const labels = labelMatch[1].split(',').map((s: string) => s.trim());
      currentCard.labels = [...(currentCard.labels || []), ...labels];
    }
  }
  if (currentCard) cards.push(currentCard);

  if (cards.length === 0) {
    console.error('  \x1b[31m  ✗ No tasks found in file. Use ## headings for task titles.\x1b[0m');
    return;
  }

  console.log(`  \x1b[36m  Found ${cards.length} tasks in "${filePath}"\x1b[0m`);
  console.log('');

  // Resolve board
  const boardsRes = await fetch(`${api}/members/me/boards?${auth}&fields=name,id`);
  const boards = await boardsRes.json() as Array<{ name: string; id: string }>;
  const board = boardName
    ? boards.find((b) => b.name.toLowerCase() === boardName.toLowerCase())
    : boards[0];

  if (!board) {
    console.error(`  \x1b[31m  ✗ Board "${boardName || '(first available)'}" not found.\x1b[0m`);
    return;
  }
  console.log(`  \x1b[90m  Board: ${board.name}\x1b[0m`);

  // Resolve list
  let targetList: { id: string; name: string } | undefined;
  if (listName) {
    const listsRes = await fetch(`${api}/boards/${board.id}/lists?${auth}&fields=name,id`);
    const lists = await listsRes.json() as Array<{ name: string; id: string }>;
    targetList = lists.find((l) => l.name.toLowerCase() === listName.toLowerCase());
    if (!targetList) {
      console.error(`  \x1b[31m  ✗ List "${listName}" not found in board "${board.name}".\x1b[0m`);
      return;
    }
  }

  // Create cards
  let created = 0;
  let failed = 0;

  for (const card of cards) {
    console.log(`  \x1b[36m  Creating: ${card.title}\x1b[0m`);

    const body = new URLSearchParams({
      name: card.title,
      desc: card.desc || '',
      idList: targetList?.id || '',
      key: secrets.TRELLO_API_KEY,
      token: secrets.TRELLO_TOKEN,
    });

    try {
      const res = await fetch(`${api}/cards?${auth}`, {
        method: 'POST',
        body,
      });
      if (res.ok) {
        created++;
        console.log(`  \x1b[32m  ✓ Created\x1b[0m`);
      } else {
        failed++;
        const errText = await res.text();
        console.log(`  \x1b[31m  ✗ Failed: ${errText.slice(0, 100)}\x1b[0m`);
      }
    } catch (err) {
      failed++;
      console.log(`  \x1b[31m  ✗ Error: ${(err as Error).message}\x1b[0m`);
    }
  }

  console.log('');
  console.log(`  \x1b[32m  ✅  Done: ${created} created, ${failed} failed\x1b[0m`);
  console.log('');
}

// ── Env ──

async function cmdEnv(): Promise<void> {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  \u2717 Trello credentials not found.\x1b[0m');
    return;
  }

  const args = process.argv.slice(3);
  const shell = args.includes('--bash')
    ? 'bash'
    : args.includes('--ps')
    ? 'ps'
    : args.includes('--cmd')
    ? 'cmd'
    : 'auto';

  const pairs: Array<[string, string]> = [
    ['TRELLO_API_KEY', secrets.TRELLO_API_KEY],
    ['TRELLO_TOKEN', secrets.TRELLO_TOKEN],
  ];

  if (shell === 'bash') {
    for (const [k, v] of pairs) console.log(`export ${k}=${v}`);
  } else if (shell === 'cmd') {
    for (const [k, v] of pairs) console.log(`set ${k}=${v}`);
  } else {
    for (const [k, v] of pairs) console.log(`$env:${k}="${v}"`);
  }
}

// ── Build ──

async function cmdBuild(): Promise<void> {
  const args = process.argv.slice(3);
  const isMcp = args.includes('--mcp') || args.includes('-m') || args.length === 0;

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║         KAEDE — Build                ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  if (isMcp) {
    const buildScript = resolve(KAEDE_DIR, 'scripts', 'build-mcp.ts');
    if (!existsSync(buildScript)) {
      console.error('  \x1b[31m  \u2717 scripts/build-mcp.ts not found\x1b[0m');
      return;
    }
    const { execSync } = await import('child_process');
    try {
      execSync(`bun ${buildScript}`, { cwd: KAEDE_DIR, stdio: 'inherit' });
    } catch (err) {
      console.error('  \x1b[31m  \u2717 Build failed:\x1b[0m', (err as Error).message);
    }
  }
}

// ── Status ──

async function cmdStatus(): Promise<void> {
  const secrets = getSecrets();
  const args = process.argv.slice(3);
  const checkMcp = args.includes('--mcp') || args.includes('-m');

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║         KAEDE — Status               \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const apiKeyOk = !!secrets.TRELLO_API_KEY;
  const tokenOk = !!secrets.TRELLO_TOKEN;

  console.log(`  Trello API Key  ${apiKeyOk ? '\x1b[32m\u2713 configured\x1b[0m' : '\x1b[31m\u2717 missing\x1b[0m'}`);
  console.log(`  Trello Token    ${tokenOk ? '\x1b[32m\u2713 configured\x1b[0m' : '\x1b[31m\u2717 missing\x1b[0m'}`);

  const globalPath = resolve(homedir(), '.config', 'kaede', 'secrets.env');
  console.log(
    `  Global secrets  ${existsSync(globalPath) ? '\x1b[32m\u2713\x1b[0m' : '\x1b[33mnot set\x1b[0m'}  \x1b[90m${globalPath}\x1b[0m`,
  );

  const devPath = resolve(KAEDE_DIR, 'secrets.env');
  if (existsSync(devPath)) {
    console.log(`  Dev secrets     \x1b[33m\u26a0\x1b[0m  \x1b[90m${devPath} (for dev/testing only)\x1b[0m`);
  }

  const globalOc = resolve(homedir(), '.config', 'opencode', 'opencode.json');
  const projectOc = resolve(process.cwd(), '.opencode', 'opencode.json');
  const hasGlobalMcp = existsSync(globalOc) && readFileSync(globalOc, 'utf-8').includes('"mcp"');
  const hasProjectMcp = existsSync(projectOc) && readFileSync(projectOc, 'utf-8').includes('"mcp"');

  let globalMcpNames: string[] = [];
  if (hasGlobalMcp) {
    try {
      const cfg = JSON.parse(readFileSync(globalOc, 'utf-8')) as { mcp?: Record<string, unknown> };
      globalMcpNames = Object.keys(cfg.mcp || {});
    } catch {}
    console.log(`  MCP configured  \x1b[32m\u2713\x1b[0m  \x1b[90m${globalOc} (global)\x1b[0m`);
    if (globalMcpNames.length > 0) {
      console.log(`  MCP servers     \x1b[90m${globalMcpNames.join(', ')}\x1b[0m`);
    }
  } else if (hasProjectMcp) {
    console.log(`  MCP configured  \x1b[32m\u2713\x1b[0m  \x1b[90m${projectOc}\x1b[0m`);
  } else {
    console.log(`  MCP configured  \x1b[33mnot configured\x1b[0m`);
  }

  if (checkMcp && apiKeyOk && tokenOk) {
    console.log('');
    console.log('  \x1b[36m  Testing MCP connection...\x1b[0m');
    try {
      const { TrelloMCPClient } = await import(resolve(KAEDE_DIR, 'src/trello-client'));
      const client = new TrelloMCPClient();
      await client.connect();
      const boards = await client.listBoards();
      console.log(`  MCP server      \x1b[32m\u2713 responding\x1b[0m \x1b[90m(${boards.length} boards)\x1b[0m`);
      client.close();
    } catch (err) {
      console.log(`  MCP server      \x1b[31m\u2717 ${(err as Error).message.slice(0, 60)}\x1b[0m`);
    }
  }

  console.log('');
  if (!apiKeyOk || !tokenOk) {
    console.log('  \x1b[33m  Run `bun scripts/kaede.ts setup` to configure.\x1b[0m');
    console.log('');
  }
}

// ── Playbook ──

async function cmdPlaybook(): Promise<void> {
  const args = process.argv.slice(3);
  const subcmd = args[0];
  if (!subcmd) {
    console.error('  \x1b[31m  \u2717 Subcommand required.\x1b[0m');
    console.log(
      '  \x1b[37m  Usage:\x1b[0m bun scripts/kaede.ts playbook \x1b[36m<parse|show>\x1b[0m \x1b[90m<path>\x1b[0m',
    );
    return;
  }

  const path = args[1];
  if (!path) {
    console.error('  \x1b[31m  \u2717 Playbook path required.\x1b[0m');
    return;
  }

  if (!existsSync(path)) {
    console.error('  \x1b[31m  \u2717 File not found: ' + path + '\x1b[0m');
    return;
  }

  const content = readFileSync(path, 'utf-8');

  if (subcmd === 'parse') {
    const { parsePlaybook } = await import(resolve(KAEDE_DIR, 'src/orchestrator'));
    const result = parsePlaybook(content);

    console.log('');
    console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
    console.log('  \x1b[35m║    KAEDE — Playbook Parser           ║\x1b[0m');
    console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
    console.log('');
    console.log(`  \x1b[90m  File: ${path}\x1b[0m`);
    console.log(`  \x1b[90m  Title: ${result.title || '(none)'}\x1b[0m`);
    console.log(`  \x1b[90m  Roles: ${result.roles.length}\x1b[0m`);
    console.log(`  \x1b[90m  Workflow lists: ${result.workflow.lists.length}\x1b[0m`);
    console.log(`  \x1b[90m  Labels: ${result.conventions.labels.length}\x1b[0m`);
    console.log('');
    for (const role of result.roles) {
      console.log(`  \x1b[36m  Role: ${role.name}\x1b[0m`);
      for (const r of role.responsibilities) {
        console.log(`     \x1b[90m  \u2022 ${r}\x1b[0m`);
      }
    }
    if (result.workflow.lists.length > 0) {
      console.log('');
      console.log('  \x1b[36m  Workflow:\x1b[0m');
      for (const list of result.workflow.lists) {
        console.log(`     \x1b[90m  ${list}\x1b[0m`);
      }
    }
    console.log('');
    console.log('  \x1b[32m  \u2705  Playbook parsed successfully.\x1b[0m');
  } else if (subcmd === 'show') {
    console.log('');
    console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
    console.log('  \x1b[35m║    KAEDE — Playbook Summary          ║\x1b[0m');
    console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
    console.log('');
    console.log(content);
  } else {
    console.error('  \x1b[31m  \u2717 Unknown subcommand: ' + subcmd + '\x1b[0m');
    console.log('  \x1b[37m  Available: parse, show\x1b[0m');
  }
}

// ── Orchestrate ──

async function cmdOrchestrate(): Promise<void> {
  const args = process.argv.slice(3);
  const getOpt = (f: string): string | undefined => {
    const i = args.indexOf(f);
    return i !== -1 ? args[i + 1] : undefined;
  };
  const playbookPath = getOpt('--playbook');
  const openkbDir = getOpt('--openkb') || resolve(process.cwd(), '.openkb');
  const opencodeDir = getOpt('--opencode') || resolve(process.cwd(), '.opencode');
  const detail = args.includes('--detail') || args.includes('-d');

  const { bundleContext } = await import(resolve(KAEDE_DIR, 'src/orchestrator'));

  const ctx = bundleContext({
    playbook: playbookPath,
    openkb: openkbDir,
    opencode: opencodeDir,
  });

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║    KAEDE — Orchestration Context     \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  if (ctx.playbook) {
    console.log(`  \x1b[36m  Playbook:\x1b[0m \x1b[90m${ctx.playbook.title}\x1b[0m`);
    console.log(
      `  \x1b[90m    ${ctx.playbook.roles.length} roles \u00B7 ${ctx.playbook.workflow.lists.length} lists \u00B7 ${ctx.playbook.conventions.labels.length} labels\x1b[0m`,
    );
    if (detail) {
      for (const r of ctx.playbook.roles) {
        console.log(`    \x1b[90m  Role: ${r.name}\x1b[0m`);
        for (const resp of r.responsibilities) console.log(`      \x1b[90m\u2022 ${resp}\x1b[0m`);
      }
      console.log(`    \x1b[90m  Lists: ${ctx.playbook.workflow.lists.join(' \u2192 ')}\x1b[0m`);
    }
  } else {
    console.log('  \x1b[33m  \u26a0  Playbook not found or not provided.\x1b[0m');
  }

  if (ctx.opencode) {
    const mcp = (ctx.opencode as Record<string, unknown>).mcp as Record<string, unknown> | undefined;
    console.log(`  \x1b[36m  OpenCode Config:\x1b[0m \x1b[90m${mcp?.trello ? '\u2713 Trello MCP' : '\u2717 No MCP'}\x1b[0m`);
  }
  console.log(`  \x1b[36m  OpenKB Glossary:\x1b[0m \x1b[90m${ctx.openkb.glossary.length} terms\x1b[0m`);

  console.log('');
  console.log('  \x1b[32m  \u2705  Context loaded. Ready for orchestration.\x1b[0m');
  console.log('');
}

// ── Run ──

interface RunResult {
  success?: boolean;
  type: string;
  name: string;
  error?: string;
}

async function cmdRun(): Promise<void> {
  const args = process.argv.slice(3);
  const getOpt = (f: string): string | undefined => {
    const i = args.indexOf(f);
    return i !== -1 ? args[i + 1] : undefined;
  };
  const playbookPath = getOpt('--playbook');
  const isDryRun = args.includes('--dry-run') || args.includes('-n');

  // Known flags that take a value (skip both flag and value)
  const knownFlagArgs = ['--playbook', '--board', '--openkb', '--opencode', '--intent'];
  // Extra args passed to intent handler (--name, --task, --list, --desc, --member, --color)
  const extraArgs: Record<string, unknown> = {};

  // Find intent and collect extra args
  let intent = getOpt('--intent') || '';
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--') || args[i].startsWith('-')) {
      if (knownFlagArgs.includes(args[i])) {
        i++; // skip next arg (value)
        continue;
      }
      // Collect extra intent args: --name value --task value etc.
      const key = args[i].replace(/^--?/, '');
      if (i + 1 < args.length && !args[i + 1].startsWith('-')) {
        extraArgs[key] = args[i + 1];
        i++;
      } else {
        extraArgs[key] = true;
      }
      continue;
    }
    intent += (intent ? ' ' : '') + args[i];
  }

  if (!intent) {
    console.error('  \x1b[31m  \u2717 Intent required.\x1b[0m');
    console.log(
      '  \x1b[37m  Usage:\x1b[0m bun scripts/kaede.ts run \x1b[36m--playbook <path>\x1b[0m \x1b[90m"intent" [--name ...] [--task ...]\x1b[0m',
    );
    console.log(
      '  \x1b[37m  Example:\x1b[0m kaede run --playbook docs/playbook-template.md "buat board" --name "Sprint 1"',
    );
    return;
  }

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║    KAEDE — Execute Intent            \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');
  console.log(`  \x1b[36m  Intent:\x1b[0m \x1b[90m"${intent}"\x1b[0m`);
  if (isDryRun) {
    console.log('  \x1b[33m  \u26a0  DRY RUN — no changes will be made.\x1b[0m');
  }

  if (playbookPath && existsSync(playbookPath)) {
    const { parsePlaybook, executeIntent } = await import(
      resolve(KAEDE_DIR, 'src/orchestrator')
    );
    const { TrelloMCPClient } = await import(resolve(KAEDE_DIR, 'src/trello-client'));

    const content = readFileSync(playbookPath, 'utf-8');
    const playbook = parsePlaybook(content);

    console.log(
      `  \x1b[36m  Playbook loaded:\x1b[0m \x1b[90m${playbook.workflow.lists.length} lists, ${playbook.roles.length} roles\x1b[0m`,
    );

    if (isDryRun) {
      console.log('');
      console.log('  \x1b[36m  Would execute:\x1b[0m \x1b[90m"' + intent + '"\x1b[0m');
      console.log(
        `  \x1b[36m  Intents available:\x1b[0m \x1b[90mmulai sprint, buat card, assign, buat label, arsipkan, pindah semua, buat board, komentar, report, tutup sprint\x1b[0m`,
      );
      console.log(`  \x1b[36m  Workflow lists:\x1b[0m \x1b[90m${playbook.workflow.lists.join(', ')}\x1b[0m`);
      console.log('');
      console.log('  \x1b[32m  \u2705  Dry run complete. Pass --board <id> to execute.\x1b[0m');
      console.log('');
      return;
    }

    console.log('');
    console.log('  \x1b[36m  Connecting to Trello MCP Server...\x1b[0m');

    const client = new TrelloMCPClient();
    try {
      await client.connect();
      console.log('  \x1b[32m  \u2713 Connected.\x1b[0m');
      console.log('');
      console.log('  \x1b[36m  Executing intent...\x1b[0m');

      let boardId = getOpt('--board');
      if (!boardId) {
        console.log('  \x1b[33m  \u26a0  No --board provided. Auto-detecting...\x1b[0m');
        try {
          const boards = await client.listBoards() as Array<{ id: string; name: string }>;
          if (boards.length === 0) {
            console.log('  \x1b[31m  \u2717 No boards found. Cannot execute.\x1b[0m');
            return;
          }
          boardId = boards[0].id;
          console.log(`  \x1b[32m  \u2713 Using board: ${boards[0].name} (${boardId})\x1b[0m`);
        } catch (err) {
          console.log(`  \x1b[31m  \u2717 Failed to auto-detect board: ${(err as Error).message}\x1b[0m`);
          return;
        }
      }
      const results = await executeIntent(client, intent, playbook, boardId, extraArgs) as RunResult[];
      console.log('');
      for (const r of results) {
        if (r.success) {
          console.log(`  \x1b[32m  \u2713 ${r.type}: ${r.name}\x1b[0m`);
        } else {
          console.log(`  \x1b[31m  \u2717 ${r.type}: ${r.name} \u2014 ${r.error}\x1b[0m`);
        }
      }

      console.log('');
      console.log('  \x1b[32m  \u2705  Intent execution completed.\x1b[0m');
    } catch (err) {
      console.error('  \x1b[31m  \u2717 Execution failed:\x1b[0m', (err as Error).message);
    } finally {
      client.close();
    }
  } else {
    console.log('  \x1b[33m  \u26a0  Playbook not provided. Execute with generic defaults.\x1b[0m');
  }
  console.log('');
}

// ── Install ──

async function cmdInstall(): Promise<void> {
  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Global Install            \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════════╝\x1b[0m');
  console.log('');

  const { execSync } = await import('child_process');
  const globalDir = KAEDE_GLOBAL_DIR;
  const kaedeConfigDir = resolve(homedir(), '.config', 'kaede');
  const opencodeConfigDir = resolve(homedir(), '.config', 'opencode');
  const opencodeConfigPath = resolve(opencodeConfigDir, 'opencode.json');

  // 1. Build MCP servers
  for (const [label, src, out] of [
    ['Trello MCP', 'packages/kaede-trello/src/mcp-server.ts', 'dist/mcp-server.js'],
    ['KAEDE Orchestrator MCP', 'src/kaede-mcp-server.ts', 'dist/kaede-mcp-server.js'],
  ] as Array<[string, string, string]>) {
    console.log(`  \x1b[36m  Building ${label}...\x1b[0m`);
    try {
      execSync(`bun build --target bun ${src} --outfile ${out}`, {
        cwd: KAEDE_DIR,
        stdio: 'inherit',
      });
      console.log(`  \x1b[32m  \u2713 ${label} built\x1b[0m`);
    } catch {
      console.log(`  \x1b[33m  \u26a0  ${label} build skipped (bun not found?)\x1b[0m`);
    }
  }

  // 2. Copy files to ~/.kaede/
  console.log(`  \x1b[36m  Installing to ${globalDir}...\x1b[0m`);
  mkdirSync(resolve(globalDir, 'dist'), { recursive: true });
  mkdirSync(resolve(globalDir, 'scripts'), { recursive: true });
  mkdirSync(resolve(globalDir, 'docs'), { recursive: true });

  try {
    const cp = (src: string, dest: string) => {
      const content = readFileSync(resolve(KAEDE_DIR, src), 'utf-8');
      writeFileSync(resolve(globalDir, dest), content, 'utf-8');
    };
    cp('dist/mcp-server.js', 'dist/mcp-server.js');
    cp('dist/kaede-mcp-server.js', 'dist/kaede-mcp-server.js');
    cp('scripts/kaede.ts', 'scripts/kaede.ts');
    cp('docs/playbook-template.md', 'docs/playbook-template.md');
    console.log('  \x1b[32m  \u2713 Files copied to ~/.kaede/\x1b[0m');
  } catch (err) {
    console.log(`  \x1b[33m  \u26a0  File copy failed: ${(err as Error).message}\x1b[0m`);
  }

  // 3. bun link (global `kaede` command)
  console.log('  \x1b[36m  Linking globally via bun link...\x1b[0m');
  try {
    execSync('bun link', { cwd: KAEDE_DIR, stdio: 'inherit' });
    console.log('  \x1b[32m  \u2713 \x1b[0m\x1b[36mkaede\x1b[0m\x1b[32m command available globally\x1b[0m');
  } catch {
    console.log('  \x1b[33m  \u26a0  bun link failed, creating fallback script...\x1b[0m');
    // Fallback: create a wrapper script
    try {
      const wrapper = `@echo off\r\nbun "${resolve(globalDir, 'scripts', 'kaede.ts').replace(/\\/g, '\\\\')}" %*\r\n`;
      writeFileSync(resolve(globalDir, 'kaede.cmd'), wrapper, 'utf-8');
      console.log(`  \x1b[33m  \u26a0  Created fallback at ${resolve(globalDir, 'kaede.cmd')}\x1b[0m`);
      console.log(
        '  \x1b[33m      Add it to your PATH or run: \x1b[0m\x1b[36msetx PATH "%PATH%;%USERPROFILE%\\.kaede"\x1b[0m',
      );
    } catch {}
  }

  // 4. Setup global OpenCode config
  console.log('  \x1b[36m  Setting up global OpenCode MCP config...\x1b[0m');
  mkdirSync(opencodeConfigDir, { recursive: true });

  let opencodeConfig: Record<string, unknown> = {};
  if (existsSync(opencodeConfigPath)) {
    try {
      opencodeConfig = JSON.parse(readFileSync(opencodeConfigPath, 'utf-8')) as Record<string, unknown>;
    } catch {}
  }

  const trelloPath = resolve(globalDir, 'dist', 'mcp-server.js').replace(/\\/g, '/');
  const kaedePath = resolve(globalDir, 'dist', 'kaede-mcp-server.js').replace(/\\/g, '/');

  const mcp = (opencodeConfig.mcp as Record<string, unknown>) || {};
  if (!mcp.trello) {
    mcp.trello = {
      type: 'local',
      command: ['bun', trelloPath],
      enabled: true,
      timeout: 30000,
    };
  }

  if (!mcp.kaede) {
    mcp.kaede = {
      type: 'local',
      command: ['bun', kaedePath],
      enabled: true,
      timeout: 60000,
    };
  }
  opencodeConfig.mcp = mcp;

  writeFileSync(opencodeConfigPath, JSON.stringify(opencodeConfig, null, 2) + '\n', 'utf-8');
  console.log('  \x1b[32m  \u2713 MCP trello & kaede added to global OpenCode config\x1b[0m');

  // 5. Setup credentials directory
  mkdirSync(kaedeConfigDir, { recursive: true });

  console.log('');
  console.log('  \x1b[32m  \u2705  KAEDE installed globally!\x1b[0m');
  console.log('');
  console.log('  \x1b[90m     Usage:\x1b[0m');
  console.log('  \x1b[90m       \x1b[36mkaede setup\x1b[0m          \u2014 setup Trello API key & token');
  console.log('  \x1b[90m       \x1b[36mkaede init\x1b[0m <dir>     \u2014 init project with KAEDE');
  console.log('  \x1b[90m       \x1b[36mkaede today\x1b[0m          \u2014 show today\'s Trello tasks');
  console.log('  \x1b[90m       \x1b[36mkaede status --mcp\x1b[0m   \u2014 check MCP connection');
  console.log('  \x1b[90m       \x1b[36mkaede run\x1b[0m "intent"   \u2014 execute intent from playbook');
  console.log('');
  console.log('  \x1b[90m     Two MCP servers registered globally in\x1b[0m');
  console.log('  \x1b[90m     ~/.config/opencode/opencode.json:\x1b[0m');
  console.log(
    '  \x1b[90m       \x1b[36mmcp.trello\x1b[0m    \u2014 kaede-trello (42 tools, fallback jika upstream tidak tersedia)\x1b[0m',
  );
  console.log('  \x1b[90m       \x1b[36mmcp.kaede\x1b[0m     \u2014 4 orchestration tools\x1b[0m');
  console.log('');
}

// ── Start API Server ──

async function cmdStart(): Promise<void> {
  const { startApiServer } = await import(resolve(KAEDE_DIR, 'src/api-server'));
  const server = await startApiServer(parseInt(process.argv[3], 10) || 3456);

  process.on('SIGINT', () => {
    console.log('\n  \x1b[33m  Shutting down API server...\x1b[0m');
    server.close();
    process.exit(0);
  });
  process.on('SIGTERM', () => {
    server.close();
    process.exit(0);
  });
}

// ── Test Tools ──

async function cmdTestTools(): Promise<void> {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  \u2717 Trello credentials not found.\x1b[0m');
    console.error('  \x1b[33m  Run `bun scripts/kaede.ts setup` first.\x1b[0m');
    return;
  }

  const { TrelloMCPClient } = await import(resolve(KAEDE_DIR, 'src/trello-client'));

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║     KAEDE — Test MCP Tools           \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const tools: Array<[string, Record<string, unknown>]> = [
    ['list_workspaces', {}],
    ['list_boards', {}],
    ['get_my_cards', {}],
  ];
  const total = tools.length;

  const client = new TrelloMCPClient();
  try {
    const timeout = setTimeout(() => {
      throw new Error('Connection timed out (30s)');
    }, 30000);
    await client.connect();
    clearTimeout(timeout);
    console.log(`  \x1b[32m  \u2713 Connected to MCP Server\x1b[0m`);
    console.log('');

    let passed = 0;
    let failed = 0;

    for (let i = 0; i < tools.length; i++) {
      const [tool, params] = tools[i];
      process.stdout.write(`  [${i + 1}/${total}] ${tool}... `);
      try {
        const result = await client.callTool(tool, params) as Record<string, unknown>;
        const summary = Object.keys(result)
          .slice(0, 3)
          .map((k) => `${k}: ${Array.isArray(result[k]) ? (result[k] as unknown[]).length : typeof result[k]}`)
          .join(', ');
        process.stdout.write(`\x1b[32m\u2713\x1b[0m \x1b[90m(${summary})\x1b[0m\n`);
        passed++;
      } catch (err) {
        process.stdout.write(`\x1b[31m\u2717\x1b[0m \x1b[90m${(err as Error).message.slice(0, 80)}\x1b[0m\n`);
        failed++;
      }
    }

    console.log('');
    console.log(`  \x1b[36m  Result: ${passed}/${total} passed, ${failed} failed\x1b[0m`);
    if (passed === total) {
      console.log('  \x1b[32m  \u2705  All MCP tools responding.\x1b[0m');
    } else {
      console.log('  \x1b[33m  \u26a0  Some tools failed. Check credentials or board config.\x1b[0m');
    }
  } catch (err) {
    console.error(`  \x1b[31m  \u2717 ${(err as Error).message}\x1b[0m`);
  } finally {
    client.close();
  }
  console.log('');
}

// ── Help ──

function cmdHelp(): void {
  console.log('');
  console.log('  \x1b[35mKAEDE — Koneksi Automated Environment DE\x1b[0m');
  console.log('  \x1b[90mCLI tool untuk manajemen Trello & AI Agent\x1b[0m');
  console.log('');
  console.log('  \x1b[37mUsage:\x1b[0m');
  console.log('    bun scripts/kaede.ts \x1b[36m<command>\x1b[0m');
  console.log('');
  console.log('  \x1b[37mCommands:\x1b[0m');
  console.log('    \x1b[36msetup\x1b[0m     \x1b[90mKonfigurasi Trello API Key & Token\x1b[0m');
  console.log('    \x1b[36mtoday\x1b[0m     \x1b[90mTampilkan task Trello hari ini\x1b[0m');
  console.log(
    '    \x1b[36minit\x1b[0m      \x1b[90mInit KAEDE di project. Flags: --playbook <path>, --tech <stack>, --db <type>\x1b[0m',
  );
  console.log('    \x1b[36mpush\x1b[0m      \x1b[90mBuat Trello cards dari file markdown\x1b[0m');
  console.log('    \x1b[36menv\x1b[0m       \x1b[90mExport credentials (--bash, --ps, --cmd)\x1b[0m');
  console.log('    \x1b[36mstatus\x1b[0m    \x1b[90mCek status konfigurasi KAEDE (--mcp untuk test koneksi)\x1b[0m');
  console.log('    \x1b[36mplaybook\x1b[0m  \x1b[90mParse/show playbook (parse <path> | show <path>)\x1b[0m');
  console.log('    \x1b[36morchestrate\x1b[0m \x1b[90mLoad context (--playbook <path> [--detail])\x1b[0m');
  console.log(
    '    \x1b[36mrun\x1b[0m       \x1b[90mExecute intent (--playbook <path> [--board <id>] [--dry-run] [--intent <intent>])\x1b[0m',
  );
  console.log('    \x1b[36mbuild\x1b[0m     \x1b[90mBuild MCP server (dist/mcp-server.js)\x1b[0m');
  console.log('    \x1b[36mstart\x1b[0m     \x1b[90mStart API server (HTTP bridge for frontend) [port]\x1b[0m');
  console.log('    \x1b[36mtest-tools\x1b[0m \x1b[90mUji koneksi 42 MCP tools (butuh Trello credentials)\x1b[0m');
  console.log('    \x1b[36minstall\x1b[0m   \x1b[90mInstall KAEDE globally via bun link\x1b[0m');
  console.log('    \x1b[36mhelp\x1b[0m      \x1b[90mTampilkan pesan ini\x1b[0m');
  console.log('');
  console.log('  \x1b[37mExamples:\x1b[0m');
  console.log('    bun scripts/kaede.ts init                              # interactive');
  console.log('    bun scripts/kaede.ts init ../project --tech Laravel --db MySQL');
  console.log('    bun scripts/kaede.ts init . --playbook playbook.md    # init + playbook ref');
  console.log('    bun scripts/kaede.ts push tasks.md                     # file mode');
  console.log('    bun scripts/kaede.ts push tasks.md --board "My Board" --list "To Do"');
  console.log('    bun scripts/kaede.ts setup');
  console.log('    bun scripts/kaede.ts today');
  console.log('    bun scripts/kaede.ts env | iex                 # Windows PowerShell');
  console.log('    bun scripts/kaede.ts env --bash | source /dev/stdin  # Linux/Mac');
  console.log('    bun scripts/kaede.ts env --cmd | cmd            # Windows CMD');
  console.log('    bun scripts/kaede.ts playbook parse ../playbook/sprint.md');
  console.log('    bun scripts/kaede.ts orchestrate --playbook ../playbook/sprint.md --detail');
  console.log('    bun scripts/kaede.ts run --playbook playbook/sprint.md --intent "Mulai Sprint Alpha"');
  console.log('    bun scripts/kaede.ts run --playbook playbook/sprint.md --board abc123 "Mulai Sprint Alpha"');
  console.log('    bun scripts/kaede.ts run --playbook playbook/sprint.md --dry-run "Mulai Sprint Alpha"');
  console.log('    bun scripts/kaede.ts status --mcp');
  console.log('    bun scripts/kaede.ts build');
  console.log('    bun scripts/kaede.ts start');
  console.log('    bun scripts/kaede.ts start 8080');
  console.log('    bun scripts/kaede.ts test-tools');
  console.log('    bun scripts/kaede.ts install');
  console.log('');
  console.log('  \x1b[37mEnv:\x1b[0m');
  console.log('    \x1b[36mKAEDE_DIR\x1b[0m   \x1b[90mOverride path ke instalasi KAEDE (default: auto-detect)\x1b[0m');
  console.log('');
}

// ─── Main ───

async function main(): Promise<void> {
  const cmd = process.argv[2] || 'help';

  switch (cmd) {
    case 'setup':
      await cmdSetup();
      break;
    case 'today':
      await cmdToday();
      break;
    case 'init':
      await cmdInit();
      break;
    case 'push':
      await cmdPush();
      break;
    case 'env':
      await cmdEnv();
      break;
    case 'build':
      await cmdBuild();
      break;
    case 'status':
      await cmdStatus();
      break;
    case 'playbook':
      await cmdPlaybook();
      break;
    case 'orchestrate':
      await cmdOrchestrate();
      break;
    case 'run':
      await cmdRun();
      break;
    case 'start':
      await cmdStart();
      break;
    case 'test-tools':
      await cmdTestTools();
      break;
    case 'install':
      await cmdInstall();
      break;
    case 'help':
    default:
      cmdHelp();
      break;
  }
  readline.close();
}

main().catch((err: Error) => {
  console.error('  \x1b[31m  ✗ Fatal:', err.message, '\x1b[0m');
  process.exit(1);
});
