/**
 * KAEDE Auth helpers — shared by `kaede auth` command group and `kaede setup`
 * onboarding. Pure functions are exported for unit testing (test/kaede-auth.test.js).
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';

export const TRELLO_API_BASE = 'https://api.trello.com/1';
export const TRELLO_AUTHORIZE_BASE = 'https://trello.com/1/authorize';

export interface Secrets {
  TRELLO_API_KEY?: string;
  TRELLO_TOKEN?: string;
  [key: string]: string | undefined;
}

export function loadEnv(filePath: string): Secrets {
  if (!existsSync(filePath)) return {};
  const content = readFileSync(filePath, 'utf-8');
  const vars: Secrets = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) vars[key] = val;
  }
  return vars;
}

/** Path global ke `~/.config/kaede/secrets.env` (dasar `home`). */
export function globalSecretsPath(home: string): string {
  return resolve(home, '.config', 'kaede', 'secrets.env');
}

/**
 * Merge `partial` ke file secrets global lalu tulis ulang.
 * Nilai `undefined`/`null` berarti menghapus kunci tersebut.
 */
export function writeGlobalSecrets(home: string, partial: Partial<Secrets>): string {
  const path = globalSecretsPath(home);
  const existing = existsSync(path) ? loadEnv(path) : {};

  for (const [k, v] of Object.entries(partial)) {
    if (v === undefined || v === null) delete existing[k];
    else existing[k] = v;
  }

  const lines = [
    '# Trello API Credentials — generated by `kaede auth login`',
    '# Keep this file secret! Do NOT commit to git.',
    '',
    ...Object.entries(existing)
      .filter(([, v]) => v !== undefined && v !== '')
      .map(([k, v]) => `${k}=${v}`),
    '',
  ];

  mkdirSync(resolve(path, '..'), { recursive: true });
  writeFileSync(path, lines.join('\n'), 'utf-8');
  return path;
}

export function buildAuthorizeUrl(
  key: string,
  opts: { returnUrl?: string } = {},
): string {
  let url = `${TRELLO_AUTHORIZE_BASE}?expiration=never&name=KAEDE&scope=read,write,account&response_type=token&key=${encodeURIComponent(key)}`;
  if (opts.returnUrl) {
    url += `&return_url=${encodeURIComponent(opts.returnUrl)}&callback_method=fragment`;
  }
  return url;
}

export function maskToken(token: string): string {
  if (!token) return '';
  return token.length <= 8 ? '••••' : `${token.slice(0, 4)}…${token.slice(-4)}`;
}

export interface TokenInfo {
  id: string;
  expires: string;
  member: { id: string; fullName: string; username: string } | null;
}

/** Validasi token per-user server-side: GET /1/tokens/{token}?key= + /member. */
export async function trelloValidateToken(key: string, token: string): Promise<TokenInfo> {
  const base = `${TRELLO_API_BASE}/tokens/${encodeURIComponent(token)}`;
  const res = await fetch(`${base}?key=${encodeURIComponent(key)}`);
  if (!res.ok) {
    throw new Error(`Trello token invalid atau expired (HTTP ${res.status}). Jalankan ulang \`kaede auth login\`.`);
  }
  const data = (await res.json()) as { id?: string; dateExpires?: string | null };

  let member: TokenInfo['member'] = null;
  try {
    const memberRes = await fetch(
      `${base}/member?key=${encodeURIComponent(key)}&fields=id,fullName,username`,
    );
    if (memberRes.ok) {
      const m = (await memberRes.json()) as { id?: string; fullName?: string; username?: string };
      member = { id: m.id || '', fullName: m.fullName || '', username: m.username || '' };
    }
  } catch {}

  return {
    id: data.id || '',
    expires: data.dateExpires || 'never',
    member,
  };
}

/** Revoke token di Trello: DELETE /1/tokens/{token}?key=. */
export async function revokeToken(key: string, token: string): Promise<boolean> {
  const res = await fetch(
    `${TRELLO_API_BASE}/tokens/${encodeURIComponent(token)}?key=${encodeURIComponent(key)}`,
    { method: 'DELETE' },
  );
  return res.ok || res.status === 404;
}

const CALLBACK_HTML = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>KAEDE — Authorized</title></head>
<body style="font-family:sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#12141f;color:#eef">
  <div style="text-align:center;max-width:420px;padding:24px">
    <h2 id="status">Authorizing…</h2>
    <p id="detail" style="color:#8a93a6;font-size:14px">Menunggu token dari Trello.</p>
  </div>
  <script>
    (function () {
      var status = document.getElementById('status');
      var detail = document.getElementById('detail');
      function done(ok, msg) {
        status.textContent = ok ? 'Authorized!' : 'Authorization failed';
        detail.textContent = msg;
      }
      try {
        var hash = window.location.hash.replace(/^#/, '');
        var token = new URLSearchParams(hash).get('token');
        if (!token) { done(false, 'Tidak ada token di URL. Tutup jendela & coba lagi.'); return; }
        fetch('/callback', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ token: token }),
        }).then(function (r) {
          done(r.ok, r.ok ? 'Akun terhubung — Anda dapat menutup jendela ini.' : 'Gagal menyimpan token.');
        }).catch(function () { done(false, 'Gagal menghubungi server lokal.'); });
      } catch (e) { done(false, String(e)); }
    })();
  </script>
</body>
</html>`;

function openBrowser(url: string): Promise<boolean> {
  const { spawn } = require('child_process');
  return new Promise((resolveOpen) => {
    let done = false;
    const finish = (ok: boolean) => {
      if (!done) { done = true; resolveOpen(ok); }
    };
    let child;
    try {
      if (process.platform === 'win32') {
        child = spawn('cmd', ['/c', 'start', '', url], { detached: true, stdio: 'ignore' });
      } else {
        const cmd = process.platform === 'darwin' ? 'open' : 'xdg-open';
        child = spawn(cmd, [url], { detached: true, stdio: 'ignore' });
      }
      child.on('error', () => finish(false));
      child.on('spawn', () => finish(true));
      setTimeout(() => finish(true), 1500);
    } catch {
      finish(false);
    }
  });
}

/**
 * Alur OAuth otomatis: ephemeral HTTP server di 127.0.0.1:<port>, buka browser
 * ke Trello dengan return_url fragment, tangkap token via POST callback.
 * Reject bila browser tak bisa dibuka atau timeout.
 */
export async function promptTokenViaLocalServer(key: string, timeoutMs = 120000): Promise<string> {
  const http = await import('node:http');
  return new Promise((resolve, reject) => {
    let settled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;

    const server = http.createServer((req, res) => {
      if (req.method === 'GET' && req.url && req.url.startsWith('/callback')) {
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
        res.end(CALLBACK_HTML);
        return;
      }
      if (req.method === 'POST' && req.url === '/callback') {
        let body = '';
        req.on('data', (c: Buffer) => (body += c.toString()));
        req.on('end', () => {
          let token = '';
          try { token = (JSON.parse(body) as { token?: string }).token || ''; } catch {}
          if (token) {
            res.writeHead(200, { 'Content-Type': 'text/plain' });
            res.end('ok');
            if (!settled) { settled = true; clearTimeout(timer); server.close(() => resolve(token)); }
          } else {
            res.writeHead(400, { 'Content-Type': 'text/plain' });
            res.end('missing token');
          }
        });
        return;
      }
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('not found');
    });

    server.on('error', (err: Error) => {
      if (!settled) { settled = true; clearTimeout(timer); reject(err); }
    });

    server.listen(0, '127.0.0.1', () => {
      const address = server.address() as { port: number };
      const url = buildAuthorizeUrl(key, { returnUrl: `http://127.0.0.1:${address.port}/callback` });
      console.log('  \x1b[90m  Membuka browser ke Trello untuk otorisasi...\x1b[0m');
      console.log('  \x1b[90m  URL: \x1b[0m' + url);
      console.log('');
      openBrowser(url).then((opened) => {
        if (!opened && !settled) {
          settled = true;
          clearTimeout(timer);
          server.close(() => reject(new Error('Browser tidak bisa dibuka. Gunakan `--manual`.')));
        }
      });
    });

    timer = setTimeout(() => {
      if (!settled) {
        settled = true;
        server.close(() => reject(new Error('Timeout menunggu OAuth callback (120s). Gunakan `--manual`.')));
      }
    }, timeoutMs);
  });
}
