#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { homedir, hostname } from 'os';
import { createInterface } from 'readline';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KAEDE_DIR = process.env.KAEDE_DIR
  ? resolve(process.env.KAEDE_DIR)
  : resolve(__dirname, '..');
const KAEDE_GLOBAL_DIR = resolve(homedir(), '.kaede');

function loadEnv(filePath) {
  if (!existsSync(filePath)) return {};
  const content = readFileSync(filePath, 'utf-8');
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) vars[key] = val;
  }
  return vars;
}

function getSecrets() {
  const global = resolve(homedir(), '.config', 'kaede', 'secrets.env');
  const local = resolve(process.cwd(), 'secrets.env');
  const dev = resolve(KAEDE_DIR, 'secrets.env');

  let merged = {};
  for (const p of [dev, local, global]) {
    merged = { ...merged, ...loadEnv(p) };
  }
  return merged;
}

let readline = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(query) {
  return new Promise((resolve) => readline.question(query, resolve));
}

// ─── Commands ───

async function cmdSetup() {
  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Setup Wizard          ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const existing = getSecrets();
  if (existing.TRELLO_API_KEY) {
    console.log(`  \x1b[33m⚠  Credentials already configured\x1b[0m`);
    console.log(`  \x1b[33m   API Key: ${existing.TRELLO_API_KEY.slice(0, 8)}...\x1b[0m`);
    const wants = await ask('  \x1b[36m  Overwrite? (y/N): \x1b[0m');
    if (wants.toLowerCase() !== 'y') {
      console.log('  \x1b[32m  OK, keeping existing credentials.\x1b[0m');
      readline.close();
      return;
    }
  }

  console.log('  \x1b[90m  ──────────────────────────────────────\x1b[0m');
  console.log('  \x1b[90m  To get Trello API credentials:\x1b[0m');
  console.log('  \x1b[90m  1. Go to https://trello.com/power-ups/admin\x1b[0m');
  console.log('  \x1b[90m  2. Create a Power-Up or use existing\x1b[0m');
  console.log('  \x1b[90m  3. Copy API Key and generate a Token\x1b[0m');
  console.log('  \x1b[90m  ──────────────────────────────────────\x1b[0m');
  console.log('');

  const apiKey = await ask('  \x1b[36m  Trello API Key: \x1b[0m');
  if (!apiKey.trim()) {
    console.log('  \x1b[31m  ✗ API Key required.\x1b[0m');
    readline.close();
    return;
  }

  const token = await ask('  \x1b[36m  Trello Token: \x1b[0m');
  if (!token.trim()) {
    console.log('  \x1b[31m  ✗ Token required.\x1b[0m');
    readline.close();
    return;
  }

  const envContent = [
    '# Trello API Credentials — generated by `kaede setup`',
    '# Keep this file secret! Do NOT commit to git.',
    '',
    `TRELLO_API_KEY=${apiKey.trim()}`,
    `TRELLO_TOKEN=${token.trim()}`,
    '',
  ].join('\n');

  const secretsPath = resolve(KAEDE_DIR, 'secrets.env');
  writeFileSync(secretsPath, envContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Saved to ${secretsPath}\x1b[0m`);

  const configDir = resolve(homedir(), '.config', 'kaede');
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }
  const globalPath = resolve(configDir, 'secrets.env');
  writeFileSync(globalPath, envContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Saved to ${globalPath} (global)\x1b[0m`);

  console.log('');
  console.log('  \x1b[32m  ✅  KAEDE credentials configured!\x1b[0m');
  console.log('  \x1b[90m     You can now run: kaede today\x1b[0m');
  console.log('');
  readline.close();
}

async function cmdToday() {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  ✗ Trello credentials not found.\x1b[0m');
    console.error('  \x1b[33m  Run `node scripts/kaede.mjs setup` first.\x1b[0m');
    return;
  }

  const { TRELLO_API_KEY, TRELLO_TOKEN } = secrets;
  const apiBase = 'https://api.trello.com/1';
  const auth = `key=${TRELLO_API_KEY}&token=${TRELLO_TOKEN}`;

  try {
    const meRes = await fetch(`${apiBase}/members/me?${auth}`);
    const me = await meRes.json();

    const boardsRes = await fetch(
      `${apiBase}/members/${me.id}/boards?${auth}&fields=name,id,url,closed&filter=open`
    );
    const boards = await boardsRes.json();

    console.log('');
    console.log(`  \x1b[35m╔══════════════════════════════════════╗\x1b[0m`);
    console.log(`  \x1b[35m║      KAEDE — Today's Tasks           ║\x1b[0m`);
    console.log(`  \x1b[35m╚══════════════════════════════════════╝\x1b[0m`);
    console.log(`  \x1b[90m  ${me.fullName || me.username} · ${new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\x1b[0m`);
    console.log('');

    let hasTasks = false;

    for (const board of boards) {
      const listsRes = await fetch(
        `${apiBase}/boards/${board.id}/lists?${auth}&fields=name,id`
      );
      const lists = await listsRes.json();

      for (const list of lists) {
        const cardsRes = await fetch(
          `${apiBase}/lists/${list.id}/cards?${auth}&fields=name,id,due,dueComplete,idMembers,url,desc,dateLastActivity&members=true`
        );
        const cards = await cardsRes.json();

        const myCards = cards.filter((c) =>
          c.idMembers && c.idMembers.includes(me.id)
        );

        if (myCards.length === 0) continue;
        hasTasks = true;

        console.log(`  \x1b[36m  ${board.name}\x1b[0m \x1b[90m→\x1b[0m \x1b[33m${list.name}\x1b[0m`);
        console.log(`  \x1b[90m  ${'─'.repeat(Math.max(board.name.length + list.name.length + 4, 20))}\x1b[0m`);

        for (const card of myCards) {
          const due = card.due
            ? new Date(card.due).toLocaleDateString('id-ID', {
                day: 'numeric',
                month: 'short',
              })
            : '';
          const isOverdue =
            card.due && new Date(card.due) < new Date() && !card.dueComplete;
          const dueStr = due
            ? ` \x1b[90m[\x1b[0m${isOverdue ? '\x1b[31m⚠ ' : '\x1b[32m'}` +
              `${due}\x1b[0m${card.dueComplete ? ' ✓' : ''}\x1b[90m]\x1b[0m`
            : '';

          console.log(`    \x1b[37m• ${card.name}\x1b[0m${dueStr}`);
          if (card.desc) {
            const firstLine = card.desc.split('\n')[0].slice(0, 80);
            console.log(`     \x1b[90m${firstLine}\x1b[0m`);
          }
        }
        console.log('');
      }
    }

    if (!hasTasks) {
      console.log('  \x1b[90m  No tasks assigned to you. Enjoy your day! 🎉\x1b[0m');
      console.log('');
    }
  } catch (err) {
    console.error('  \x1b[31m  ✗ Failed to fetch Trello data:\x1b[0m', err.message);
  }
}

async function cmdInit() {
  // Parse args: [dir] [--name X] [--tech X] [--db X]
  const args = process.argv.slice(3);
  const targetDir = resolve(args.find((_, i, a) => !a[i].startsWith('-')) || process.cwd());
  const getOpt = (flag) => { const i = args.indexOf(flag); return i !== -1 ? args[i + 1] : undefined; };
  const optName = getOpt('--name');
  const optTech = getOpt('--tech');
  const optDb = getOpt('--db');
  const optPlaybook = getOpt('--playbook');
  const interactive = !optTech || !optDb; // skip prompts when --tech & --db given

  const projectName = optName || basename(targetDir);
  const opencodeDir = resolve(targetDir, '.opencode');
  const sharedDir = resolve(opencodeDir, 'SHARED');
  const opencodeJsonPath = resolve(opencodeDir, 'opencode.json');

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║      KAEDE — Project Init            ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  // 1. Check credentials
  const secrets = getSecrets();
  const hasCreds = !!(secrets.TRELLO_API_KEY && secrets.TRELLO_TOKEN);
  if (!hasCreds && interactive) {
    const globalPath = resolve(homedir(), '.config', 'kaede', 'secrets.env');
    if (!existsSync(globalPath)) {
      console.log('  \x1b[33m  ⚠  Trello credentials not found.\x1b[0m');
      const wantsSetup = await ask('  \x1b[36m  Run setup now? (Y/n): \x1b[0m');
      if (wantsSetup.toLowerCase() !== 'n') {
        readline.close();
        await cmdSetup();
        console.log('');
        const { createInterface } = await import('readline');
        readline = createInterface({ input: process.stdin, output: process.stdout });
      } else {
        console.log('  \x1b[33m  ⚠  Skipping credentials. Run `kaede setup` later.\x1b[0m');
        console.log('');
      }
    } else {
      console.log(`  \x1b[32m  ✓ Global credentials found at ${globalPath}\x1b[0m`);
    }
  }

  // 2. Get project info (interactive or from args)
  let techStack = optTech;
  let dbType = optDb;
  if (interactive) {
    techStack = await ask('  \x1b[36m  Tech stack (e.g. Laravel, Node.js, Next.js): \x1b[0m') || projectName;
    dbType = await ask('  \x1b[36m  Database (e.g. MySQL, PostgreSQL, SQLite): \x1b[0m') || '—';
  }

  // 3. Create directory structure
  mkdirSync(sharedDir, { recursive: true });
  console.log(`  \x1b[90m  📁 ${opencodeDir}\x1b[0m`);
  console.log(`  \x1b[90m  📁 ${sharedDir}\x1b[0m`);

  // 4. Generate project-context.md
  const contextPath = resolve(sharedDir, 'project-context.md');
  const contextContent = [
    `# Project Context — ${projectName}`,
    '',
    '## Ringkasan',
    '',
    '## Tech Stack',
    `- **Framework**: ${techStack}`,
    `- **Database**: ${dbType}`,
    '',
    '## Aturan Penting',
    '1. Semua perubahan \`main\` harus via PR dengan minimal 1 review',
    '2. Commit menggunakan Conventional Commits',
    '3. Coding style mengikuti standar project',
    '4. Test harus hijau sebelum merge',
    '5. \`.env\`, key, token tidak boleh di-commit',
    '',
    '## Tim',
    '| Person | Role |',
    '|---|---|',
    '',
  ].join('\n');
  writeFileSync(contextPath, contextContent, 'utf-8');
  console.log(`  \x1b[32m  ✓ Generated ${contextPath}\x1b[0m`);

  // 5. Generate agent-rules.md
  const rulesPath = resolve(sharedDir, 'agent-rules.md');
  const rulesContent = [
    `# Agent Rules — ${projectName}`,
    '',
    '## Aturan Umum',
    '- Gunakan bahasa Indonesia',
    '- Jawab ringkas, langsung ke titik',
    '- Ikuti pattern kode yang sudah ada',
    '- Jangan tambah komentar kecuali diminta',
    '- Jika ragu, tanya dulu',
    '',
    '## Konvensi Commit',
    '```',
    'feat:      Fitur baru',
    'fix:       Perbaikan bug',
    'docs:      Dokumentasi',
    'chore:     Maintenance',
    'refactor:  Refaktor kode',
    'test:      Penambahan test',
    '```',
    '',
    '## Keamanan',
    '- Jangan commit \`.env\`, key, token, password',
    '- Input user divalidasi & di-sanitize',
    '',
  ].join('\n');
  if (!existsSync(rulesPath)) {
    writeFileSync(rulesPath, rulesContent, 'utf-8');
    console.log(`  \x1b[32m  ✓ Generated ${rulesPath}\x1b[0m`);
  } else {
    console.log(`  \x1b[33m  ⚠  ${rulesPath} already exists, skipping\x1b[0m`);
  }

  // 6. Generate or update opencode.json
  let config = {};
  if (existsSync(opencodeJsonPath)) {
    try {
      config = JSON.parse(readFileSync(opencodeJsonPath, 'utf-8'));
    } catch {
      console.error('  \x1b[31m  ✗ Invalid existing opencode.json, creating fresh\x1b[0m');
      config = {};
    }
  }

  // Note: MCP trello is configured globally at ~/.config/opencode/opencode.json
  // No need to duplicate MCP config at project level.
  // If custom MCP needed, add it here.

  // Instructions
  if (!config.instructions) {
    config.instructions = [
      '.opencode/SHARED/project-context.md',
      '.opencode/SHARED/agent-rules.md',
    ];
  }

  // References
  if (!config.references) {
    config.references = {
      kaede: {
        path: KAEDE_GLOBAL_DIR.replace(/\\/g, '/'),
        description: 'KAEDE — Trello MCP, CLI tools & AI Agent ecosystem',
      },
      docs: {
        path: 'docs',
        description: 'Dokumentasi project',
      },
    };
  }

  // Add playbook reference if --playbook given
  if (optPlaybook && !config.references.playbook) {
    const playbookRel = relative(targetDir, resolve(targetDir, optPlaybook)).replace(/\\/g, '/');
    config.references.playbook = {
      path: playbookRel.startsWith('..') ? playbookRel : playbookRel,
      description: 'Playbook — SOP, workflow, standar tim',
    };
  }

  // Agents
  if (!config.agent) {
    config.agent = {
      build: {
        description: 'Agent utama — development & maintenance',
        mode: 'primary',
        permission: { edit: 'allow', bash: 'ask' },
      },
      plan: {
        description: 'Agent perencanaan — arsitektur & desain',
        mode: 'primary',
        permission: { edit: 'deny' },
      },
    };
  }

  // Commands (uses global `kaede` CLI — install via `kaede install`)
  if (!config.command) {
    config.command = {
      'kaede-today': {
        description: 'Tampilkan task Trello hari ini',
        template: 'kaede today',
      },
      'kaede-status': {
        description: 'Cek status konfigurasi KAEDE',
        template: 'kaede status',
      },
      'kaede-setup': {
        description: 'Setup Trello API Key & Token',
        template: 'kaede setup',
      },
      'kaede-run': {
        description: 'Eksekusi intent ke Trello dari playbook',
        template: 'kaede run --playbook $ARGUMENTS',
      },
      'kaede-push': {
        description: 'Buat Trello cards dari file markdown (.md)',
        template: 'kaede push $ARGUMENTS',
      },
    };
  }

  if (!config.default_agent) {
    config.default_agent = 'build';
  }
  if (!config['$schema']) {
    config['$schema'] = 'https://opencode.ai/config.json';
  }

  writeFileSync(opencodeJsonPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  console.log(`  \x1b[32m  ✓ Updated ${opencodeJsonPath}\x1b[0m`);

  // 7. Copy secrets.env (from global or KAEDE local)
  const secretsDest = resolve(targetDir, 'secrets.env');
  if (!existsSync(secretsDest)) {
    const globalSecrets = resolve(homedir(), '.config', 'kaede', 'secrets.env');
    const localSecrets = resolve(KAEDE_DIR, 'secrets.env');
    let sourceSecrets = null;
    if (existsSync(globalSecrets)) sourceSecrets = globalSecrets;
    else if (existsSync(localSecrets)) sourceSecrets = localSecrets;

    if (sourceSecrets) {
      const content = readFileSync(sourceSecrets, 'utf-8');
      writeFileSync(secretsDest, content, 'utf-8');
      console.log(`  \x1b[32m  ✓ Copied credentials to ${secretsDest}\x1b[0m`);
    }
  } else {
    console.log(`  \x1b[33m  ⚠  ${secretsDest} already exists, skipping\x1b[0m`);
  }

  // 8. Update .gitignore
  const gitignorePath = resolve(targetDir, '.gitignore');
  let gitignore = '';
  if (existsSync(gitignorePath)) {
    gitignore = readFileSync(gitignorePath, 'utf-8');
  }
  const entries = ['secrets.env', '.opencode/'];
  for (const entry of entries) {
    if (!gitignore.includes(entry)) {
      gitignore += (gitignore.endsWith('\n') || gitignore === '' ? '' : '\n') + entry + '\n';
    }
  }
  writeFileSync(gitignorePath, gitignore, 'utf-8');
  console.log(`  \x1b[32m  ✓ Updated ${gitignorePath}\x1b[0m`);

  // 9. Summary
  console.log('');
  console.log('  \x1b[32m  ✅  KAEDE initialized!\x1b[0m');
  console.log(`  \x1b[90m     Project: ${projectName}\x1b[0m`);
  console.log(`  \x1b[90m     Target:  ${targetDir}\x1b[0m`);
  console.log(`  \x1b[90m     MCP:     trello (global config ~/.config/opencode/)\x1b[0m`);
  console.log('');
  console.log('  \x1b[90m  Next steps:\x1b[0m');
  console.log('  \x1b[90m  1. Edit .opencode/SHARED/project-context.md dengan info project\x1b[0m');
  console.log('  \x1b[90m  2. Copy & edit playbook: \x1b[0m\x1b[36mkaede init . --playbook playbook.md\x1b[0m');
  console.log('  \x1b[90m  3. Jalankan \x1b[0m\x1b[36mopencode\x1b[0m\x1b[90m — MCP trello otomatis tersedia\x1b[0m');
  console.log('  \x1b[90m  4. Cek task Trello: \x1b[0m\x1b[36mkaede today\x1b[0m');
  console.log('');
}

function parseCards(content) {
  const lines = content.split('\n');
  const cards = [];
  let current = null;

  for (const line of lines) {
    const t = line.trim();

    if (!t) {
      if (current) current.desc += '\n';
      continue;
    }

    const heading = t.match(/^##\s+(.+)/);
    if (heading) {
      if (current && current.title) cards.push(current);
      current = { title: heading[1], desc: '' };
      continue;
    }

    const task = t.match(/^[-*]\s+\[\s*[x ]?\s*\]\s+(.+)/);
    if (task) {
      if (current && current.title) cards.push(current);
      current = { title: task[1], desc: '' };
      continue;
    }

    if (!current) current = { title: '', desc: '' };
    if (!current.title) {
      current.title = t;
    } else {
      current.desc += (current.desc ? '\n' : '') + t;
    }
  }

  if (current && current.title) cards.push(current);
  for (const c of cards) { c.desc = c.desc.trim(); if (!c.desc) delete c.desc; }
  return cards;
}

async function cmdPush() {
  const args = process.argv.slice(3);
  const getOpt = (f) => { const i = args.indexOf(f); return i !== -1 ? args[i + 1] : undefined; };
  const boardName = getOpt('--board');
  const listName = getOpt('--list');
  const filePath = args.find((_, i, a) => !a[i].startsWith('-'));

  let content;
  if (filePath) {
    if (!existsSync(filePath)) {
      console.error('  \x1b[31m  ✗ File not found: ' + filePath + '\x1b[0m');
      return;
    }
    content = readFileSync(filePath, 'utf-8');
  } else {
    readline.close();
    process.stdin.setEncoding('utf-8');
    content = await new Promise((r) => {
      let d = '';
      process.stdin.on('data', (c) => { d += c; });
      process.stdin.on('end', () => r(d));
      if (process.stdin.isTTY) process.stdin.resume();
    });
    if (!content.trim()) {
      console.error('  \x1b[31m  ✗ No content provided.\x1b[0m');
      return;
    }
  }

  const cards = parseCards(content.trim());
  if (cards.length === 0) {
    console.error('  \x1b[31m  ✗ No cards could be parsed from content.\x1b[0m');
    return;
  }

  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  ✗ Trello credentials not found. Run `kaede setup` first.\x1b[0m');
    return;
  }

  const auth = `key=${secrets.TRELLO_API_KEY}&token=${secrets.TRELLO_TOKEN}`;
  const api = 'https://api.trello.com/1';

  try {
    const boards = await (await fetch(`${api}/members/me/boards?${auth}&fields=name,id,url&filter=open`)).json();

    let board;
    if (boardName) {
      board = boards.find((b) => b.name.toLowerCase().includes(boardName.toLowerCase()));
      if (!board) {
        console.error('  \x1b[31m  ✗ Board "' + boardName + '" not found.\x1b[0m');
        console.error('  \x1b[90m  Available: ' + boards.map((b) => b.name).join(', ') + '\x1b[0m');
        return;
      }
    } else {
      board = boards[0];
      console.log('  \x1b[90m  Board: ' + board.name + ' (use --board to change)\x1b[0m');
    }

    const lists = await (await fetch(`${api}/boards/${board.id}/lists?${auth}&fields=name,id`)).json();
    let targetList;
    if (listName) {
      targetList = lists.find((l) => l.name.toLowerCase().includes(listName.toLowerCase()));
      if (!targetList) {
        console.error('  \x1b[31m  ✗ List "' + listName + '" not found.\x1b[0m');
        console.error('  \x1b[90m  Available: ' + lists.map((l) => l.name).join(', ') + '\x1b[0m');
        return;
      }
    } else {
      targetList = lists.find((l) => !l.closed) || lists[0];
      console.log('  \x1b[90m  List: ' + targetList.name + ' (use --list to change)\x1b[0m');
    }

    console.log('');
    console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
    console.log('  \x1b[35m║        KAEDE — Card Push             ║\x1b[0m');
    console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
    console.log('');
    console.log('  \x1b[90m  ' + board.name + ' → ' + targetList.name + '\x1b[0m');
    console.log('  \x1b[90m  ' + cards.length + ' card(s)\x1b[0m');
    console.log('');

    for (let i = 0; i < cards.length; i++) {
      const c = cards[i];
      console.log('  \x1b[36m  ' + (i + 1) + '. ' + c.title + '\x1b[0m');
      if (c.desc) {
        const p = c.desc.replace(/\n/g, ' ').slice(0, 90);
        console.log('     \x1b[90m' + p + (c.desc.length > 90 ? '...' : '') + '\x1b[0m');
      }
    }
    console.log('');

    if (process.stdin.isTTY) {
      const ok = await ask('  \x1b[36m  Create ' + cards.length + ' card(s)? (Y/n): \x1b[0m');
      if (ok.toLowerCase() === 'n') {
        console.log('  \x1b[33m  Cancelled.\x1b[0m');
        return;
      }
    } else {
      console.log('  \x1b[90m  (auto-confirming — pipe mode)\x1b[0m');
    }

    for (const card of cards) {
      const body = new URLSearchParams({
        name: card.title,
        desc: card.desc || '',
        idList: targetList.id,
        key: secrets.TRELLO_API_KEY,
        token: secrets.TRELLO_TOKEN,
      });

      const res = await fetch(`${api}/cards`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: body.toString(),
      });

      if (res.ok) {
        const created = await res.json();
        console.log('  \x1b[32m  ✓ ' + card.title + '\x1b[0m \x1b[90m' + created.url + '\x1b[0m');
      } else {
        const err = await res.text();
        console.error('  \x1b[31m  ✗ ' + card.title + ' — ' + (res.statusText || err.slice(0, 100)) + '\x1b[0m');
      }
    }

    console.log('');
    console.log('  \x1b[32m  ✅  ' + cards.length + ' card(s) created.\x1b[0m');
  } catch (err) {
    console.error('  \x1b[31m  ✗ Error:\x1b[0m', err.message);
  }
}

async function cmdEnv() {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  ✗ Trello credentials not found.\x1b[0m');
    return;
  }

  if (process.platform === 'win32') {
    console.log(`$env:TRELLO_API_KEY="${secrets.TRELLO_API_KEY}"`);
    console.log(`$env:TRELLO_TOKEN="${secrets.TRELLO_TOKEN}"`);
  } else {
    console.log(`export TRELLO_API_KEY="${secrets.TRELLO_API_KEY}"`);
    console.log(`export TRELLO_TOKEN="${secrets.TRELLO_TOKEN}"`);
  }
}

async function cmdBuild() {
  const args = process.argv.slice(3);
  const isMcp = args.includes('--mcp') || args.includes('-m') || args.length === 0;

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║         KAEDE — Build                ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  if (isMcp) {
    const buildScript = resolve(KAEDE_DIR, 'scripts', 'build-mcp.mjs');
    if (!existsSync(buildScript)) {
      console.error('  \x1b[31m  ✗ scripts/build-mcp.mjs not found\x1b[0m');
      return;
    }
    const { execSync } = await import('child_process');
    try {
      execSync(`bun ${buildScript}`, { cwd: KAEDE_DIR, stdio: 'inherit' });
    } catch (err) {
      console.error('  \x1b[31m  ✗ Build failed:\x1b[0m', err.message);
    }
  }
}

async function cmdStatus() {
  const secrets = getSecrets();
  const args = process.argv.slice(3);
  const checkMcp = args.includes('--mcp') || args.includes('-m');

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║         KAEDE — Status               \x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const apiKeyOk = !!secrets.TRELLO_API_KEY;
  const tokenOk = !!secrets.TRELLO_TOKEN;

  console.log(`  Trello API Key  ${apiKeyOk ? '\x1b[32m✓ configured\x1b[0m' : '\x1b[31m✗ missing\x1b[0m'}`);
  console.log(`  Trello Token    ${tokenOk ? '\x1b[32m✓ configured\x1b[0m' : '\x1b[31m✗ missing\x1b[0m'}`);

  const globalPath = resolve(homedir(), '.config', 'kaede', 'secrets.env');
  console.log(`  Global secrets  ${existsSync(globalPath) ? '\x1b[32m✓\x1b[0m' : '\x1b[33mnot set\x1b[0m'}  \x1b[90m${globalPath}\x1b[0m`);

  const devPath = resolve(KAEDE_DIR, 'secrets.env');
  if (existsSync(devPath)) {
    console.log(`  Dev secrets     \x1b[33m⚠\x1b[0m  \x1b[90m${devPath} (for dev/testing only)\x1b[0m`);
  }

  const globalOc = resolve(homedir(), '.config', 'opencode', 'opencode.json');
  const projectOc = resolve(process.cwd(), '.opencode', 'opencode.json');
  const hasGlobalMcp = existsSync(globalOc) && readFileSync(globalOc, 'utf-8').includes('"mcp"');
  const hasProjectMcp = existsSync(projectOc) && readFileSync(projectOc, 'utf-8').includes('"mcp"');

  let globalMcpNames = [];
  if (hasGlobalMcp) {
    try {
      const cfg = JSON.parse(readFileSync(globalOc, 'utf-8'));
      globalMcpNames = Object.keys(cfg.mcp || {});
    } catch {}
    console.log(`  MCP configured  \x1b[32m✓\x1b[0m  \x1b[90m${globalOc} (global)\x1b[0m`);
    if (globalMcpNames.length > 0) {
      console.log(`  MCP servers     \x1b[90m${globalMcpNames.join(', ')}\x1b[0m`);
    }
  } else if (hasProjectMcp) {
    console.log(`  MCP configured  \x1b[32m✓\x1b[0m  \x1b[90m${projectOc}\x1b[0m`);
  } else {
    console.log(`  MCP configured  \x1b[33mnot configured\x1b[0m`);
  }

  if (checkMcp && apiKeyOk && tokenOk) {
    console.log('');
    console.log('  \x1b[36m  Testing MCP connection...\x1b[0m');
    try {
      const { TrelloMCPClient } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'trello-client.js')).href);
      const client = new TrelloMCPClient();
      await client.connect();
      const boards = await client.listBoards();
      console.log(`  MCP server      \x1b[32m✓ responding\x1b[0m \x1b[90m(${boards.length} boards)\x1b[0m`);
      client.close();
    } catch (err) {
      console.log(`  MCP server      \x1b[31m✗ ${err.message.slice(0, 60)}\x1b[0m`);
    }
  }

  console.log('');
  if (!apiKeyOk || !tokenOk) {
    console.log('  \x1b[33m  Run `node scripts/kaede.mjs setup` to configure.\x1b[0m');
    console.log('');
  }
}

async function cmdPlaybook() {
  const args = process.argv.slice(3);
  const subcmd = args[0];
  if (!subcmd) {
    console.error('  \x1b[31m  ✗ Subcommand required.\x1b[0m');
    console.log('  \x1b[37m  Usage:\x1b[0m node scripts/kaede.mjs playbook \x1b[36m<parse|show>\x1b[0m \x1b[90m<path>\x1b[0m');
    return;
  }

  const path = args[1];
  if (!path) {
    console.error('  \x1b[31m  ✗ Playbook path required.\x1b[0m');
    return;
  }

  if (!existsSync(path)) {
    console.error('  \x1b[31m  ✗ File not found: ' + path + '\x1b[0m');
    return;
  }

  const content = readFileSync(path, 'utf-8');

  if (subcmd === 'parse') {
    const { parsePlaybook } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'orchestrator.js')).href);
    const result = parsePlaybook(content);

    console.log('');
    console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
    console.log('  \x1b[35m║    KAEDE — Playbook Parser           ║\x1b[0m');
    console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
    console.log('');
    console.log(`  \x1b[90m  File: ${path}\x1b[0m`);
    console.log(`  \x1b[90m  Title: ${result.title || '(none)'}\x1b[0m`);
    console.log(`  \x1b[90m  Roles: ${result.roles.length}\x1b[0m`);
    console.log(`  \x1b[90m  Workflow lists: ${result.workflow.lists.length}\x1b[0m`);
    console.log(`  \x1b[90m  Labels: ${result.conventions.labels.length}\x1b[0m`);
    console.log('');
    for (const role of result.roles) {
      console.log(`  \x1b[36m  Role: ${role.name}\x1b[0m`);
      for (const r of role.responsibilities) {
        console.log(`     \x1b[90m  • ${r}\x1b[0m`);
      }
    }
    if (result.workflow.lists.length > 0) {
      console.log('');
      console.log('  \x1b[36m  Workflow:\x1b[0m');
      for (const list of result.workflow.lists) {
        console.log(`     \x1b[90m  ${list}\x1b[0m`);
      }
    }
    console.log('');
    console.log('  \x1b[32m  ✅  Playbook parsed successfully.\x1b[0m');
  } else if (subcmd === 'show') {
    console.log('');
    console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
    console.log('  \x1b[35m║    KAEDE — Playbook Summary          ║\x1b[0m');
    console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
    console.log('');
    console.log(content);
  } else {
    console.error('  \x1b[31m  ✗ Unknown subcommand: ' + subcmd + '\x1b[0m');
    console.log('  \x1b[37m  Available: parse, show\x1b[0m');
  }
}

async function cmdOrchestrate() {
  const args = process.argv.slice(3);
  const getOpt = (f) => { const i = args.indexOf(f); return i !== -1 ? args[i + 1] : undefined; };
  const playbookPath = getOpt('--playbook');
  const openkbDir = getOpt('--openkb') || resolve(process.cwd(), '.openkb');
  const opencodeDir = getOpt('--opencode') || resolve(process.cwd(), '.opencode');
  const detail = args.includes('--detail') || args.includes('-d');

  const { bundleContext } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'orchestrator.js')).href);

  const ctx = bundleContext({
    playbook: playbookPath,
    openkb: openkbDir,
    opencode: opencodeDir,
  });

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║    KAEDE — Orchestration Context     ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  if (ctx.playbook) {
    console.log(`  \x1b[36m  Playbook:\x1b[0m \x1b[90m${ctx.playbook.title}\x1b[0m`);
    console.log(`  \x1b[90m    ${ctx.playbook.roles.length} roles · ${ctx.playbook.workflow.lists.length} lists · ${ctx.playbook.conventions.labels.length} labels\x1b[0m`);
    if (detail) {
      for (const r of ctx.playbook.roles) {
        console.log(`    \x1b[90m  Role: ${r.name}\x1b[0m`);
        for (const resp of r.responsibilities) console.log(`      \x1b[90m• ${resp}\x1b[0m`);
      }
      console.log(`    \x1b[90m  Lists: ${ctx.playbook.workflow.lists.join(' → ')}\x1b[0m`);
    }
  } else {
    console.log('  \x1b[33m  ⚠  Playbook not found or not provided.\x1b[0m');
  }

  console.log(`  \x1b[36m  OpenKB Glossary:\x1b[0m \x1b[90m${ctx.openkb.glossary.length} terms\x1b[0m`);
  console.log(`  \x1b[36m  OpenCode Config:\x1b[0m \x1b[90m${ctx.opencode?.mcp?.trello ? '✓ Trello MCP' : '✗ No MCP'}\x1b[0m`);

  console.log('');
  console.log('  \x1b[32m  ✅  Context loaded. Ready for orchestration.\x1b[0m');
  console.log('');
}

async function cmdRun() {
  const args = process.argv.slice(3);
  const getOpt = (f) => { const i = args.indexOf(f); return i !== -1 ? args[i + 1] : undefined; };
  const playbookPath = getOpt('--playbook');
  const isDryRun = args.includes('--dry-run') || args.includes('-n');

  // Known flags that take a value (skip both flag and value)
  const knownFlagArgs = ['--playbook', '--board', '--openkb', '--opencode'];
  // Extra args passed to intent handler (--name, --task, --list, --desc, --member, --color)
  const extraArgs = {};

  // Find intent and collect extra args
  let intent = '';
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--') || args[i].startsWith('-')) {
      if (knownFlagArgs.includes(args[i])) {
        i++; // skip next arg (value)
        continue;
      }
      // Collect extra intent args: --name value --task value etc.
      const key = args[i].replace(/^--?/, '');
      if (i + 1 < args.length && !args[i + 1].startsWith('-')) {
        extraArgs[key] = args[i + 1];
        i++;
      } else {
        extraArgs[key] = true;
      }
      continue;
    }
    intent += (intent ? ' ' : '') + args[i];
  }

  if (!intent) {
    console.error('  \x1b[31m  ✗ Intent required.\x1b[0m');
    console.log('  \x1b[37m  Usage:\x1b[0m node scripts/kaede.mjs run \x1b[36m--playbook <path>\x1b[0m \x1b[90m"intent" [--name ...] [--task ...]\x1b[0m');
    console.log('  \x1b[37m  Example:\x1b[0m kaede run --playbook docs/playbook-template.md "buat board" --name "Sprint 1"');
    return;
  }

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║    KAEDE — Execute Intent            ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');
  console.log(`  \x1b[36m  Intent:\x1b[0m \x1b[90m"${intent}"\x1b[0m`);
  if (isDryRun) {
    console.log('  \x1b[33m  ⚠  DRY RUN — no changes will be made.\x1b[0m');
  }

  if (playbookPath && existsSync(playbookPath)) {
    const { parsePlaybook, executeIntent } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'orchestrator.js')).href);
    const { TrelloMCPClient } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'trello-client.js')).href);

    const content = readFileSync(playbookPath, 'utf-8');
    const playbook = parsePlaybook(content);

    console.log(`  \x1b[36m  Playbook loaded:\x1b[0m \x1b[90m${playbook.workflow.lists.length} lists, ${playbook.roles.length} roles\x1b[0m`);

    if (isDryRun) {
      console.log('');
      console.log('  \x1b[36m  Would execute:\x1b[0m \x1b[90m"' + intent + '"\x1b[0m');
      console.log(`  \x1b[36m  Intents available:\x1b[0m \x1b[90mmulai sprint, buat card, assign, buat label, arsipkan, pindah semua, buat board, komentar, report, tutup sprint\x1b[0m`);
      console.log(`  \x1b[36m  Workflow lists:\x1b[0m \x1b[90m${playbook.workflow.lists.join(', ')}\x1b[0m`);
      console.log('');
      console.log('  \x1b[32m  ✅  Dry run complete. Pass --board <id> to execute.\x1b[0m');
      console.log('');
      return;
    }

    console.log('');
    console.log('  \x1b[36m  Connecting to Trello MCP Server...\x1b[0m');

    const client = new TrelloMCPClient();
    try {
      await client.connect();
      console.log('  \x1b[32m  ✓ Connected.\x1b[0m');
      console.log('');
      console.log('  \x1b[36m  Executing intent...\x1b[0m');

      let boardId = getOpt('--board');
      if (!boardId) {
        console.log('  \x1b[33m  ⚠  No --board provided. Auto-detecting...\x1b[0m');
        try {
          const boards = await client.listBoards();
          if (boards.length === 0) {
            console.log('  \x1b[31m  ✗ No boards found. Cannot execute.\x1b[0m');
            return;
          }
          boardId = boards[0].id;
          console.log(`  \x1b[32m  ✓ Using board: ${boards[0].name} (${boardId})\x1b[0m`);
        } catch (err) {
          console.log(`  \x1b[31m  ✗ Failed to auto-detect board: ${err.message}\x1b[0m`);
          return;
        }
      }
      const results = await executeIntent(client, intent, playbook, boardId, extraArgs);
      console.log('');
      for (const r of results) {
        if (r.success) {
          console.log(`  \x1b[32m  ✓ ${r.type}: ${r.name}\x1b[0m`);
        } else {
          console.log(`  \x1b[31m  ✗ ${r.type}: ${r.name} — ${r.error}\x1b[0m`);
        }
      }

      console.log('');
      console.log('  \x1b[32m  \u2705  Intent execution completed.\x1b[0m');
    } catch (err) {
      console.error('  \x1b[31m  ✗ Execution failed:\x1b[0m', err.message);
    } finally {
      client.close();
    }
  } else {
    console.log('  \x1b[33m  ⚠  Playbook not provided. Execute with generic defaults.\x1b[0m');
  }
  console.log('');
}

async function cmdInstall() {
  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║        KAEDE — Global Install            ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════════╝\x1b[0m');
  console.log('');

  const { execSync } = await import('child_process');
  const globalDir = KAEDE_GLOBAL_DIR;
  const kaedeConfigDir = resolve(homedir(), '.config', 'kaede');
  const opencodeConfigDir = resolve(homedir(), '.config', 'opencode');
  const opencodeConfigPath = resolve(opencodeConfigDir, 'opencode.json');

  // 1. Build MCP servers
  for (const [label, src, out] of [
    ['Trello MCP', 'src/mcp-server.js', 'dist/mcp-server.js'],
    ['KAEDE Orchestrator MCP', 'src/kaede-mcp-server.js', 'dist/kaede-mcp-server.js'],
  ]) {
    console.log(`  \x1b[36m  Building ${label}...\x1b[0m`);
    try {
      execSync(`bun build --target bun ${src} --outfile ${out}`, {
        cwd: KAEDE_DIR,
        stdio: 'inherit',
      });
      console.log(`  \x1b[32m  ✓ ${label} built\x1b[0m`);
    } catch {
      console.log(`  \x1b[33m  ⚠  ${label} build skipped (bun not found?)\x1b[0m`);
    }
  }

  // 2. Copy files to ~/.kaede/
  console.log(`  \x1b[36m  Installing to ${globalDir}...\x1b[0m`);
  mkdirSync(resolve(globalDir, 'dist'), { recursive: true });
  mkdirSync(resolve(globalDir, 'scripts'), { recursive: true });
  mkdirSync(resolve(globalDir, 'docs'), { recursive: true });

  try {
    const cp = (src, dest) => {
      const content = readFileSync(resolve(KAEDE_DIR, src), 'utf-8');
      writeFileSync(resolve(globalDir, dest), content, 'utf-8');
    };
    cp('dist/mcp-server.js', 'dist/mcp-server.js');
    cp('dist/kaede-mcp-server.js', 'dist/kaede-mcp-server.js');
    cp('scripts/kaede.mjs', 'scripts/kaede.mjs');
    cp('docs/playbook-template.md', 'docs/playbook-template.md');
    console.log('  \x1b[32m  ✓ Files copied to ~/.kaede/\x1b[0m');
  } catch (err) {
    console.log(`  \x1b[33m  ⚠  File copy failed: ${err.message}\x1b[0m`);
  }

  // 3. npm link (global `kaede` command)
  console.log('  \x1b[36m  Linking globally via npm link...\x1b[0m');
  try {
    execSync('npm link', { cwd: KAEDE_DIR, stdio: 'inherit' });
    console.log('  \x1b[32m  ✓ \x1b[0m\x1b[36mkaede\x1b[0m\x1b[32m command available globally\x1b[0m');
  } catch {
    console.log('  \x1b[33m  ⚠  npm link failed, creating fallback script...\x1b[0m');
    // Fallback: create a wrapper script
    try {
      const wrapper = `@echo off\r\nnode "${resolve(globalDir, 'scripts', 'kaede.mjs').replace(/\\/g, '\\\\')}" %*\r\n`;
      writeFileSync(resolve(globalDir, 'kaede.cmd'), wrapper, 'utf-8');
      console.log(`  \x1b[33m  ⚠  Created fallback at ${resolve(globalDir, 'kaede.cmd')}\x1b[0m`);
      console.log('  \x1b[33m      Add it to your PATH or run: \x1b[0m\x1b[36msetx PATH "%PATH%;%USERPROFILE%\\.kaede"\x1b[0m');
    } catch {}
  }

  // 4. Setup global OpenCode config
  console.log('  \x1b[36m  Setting up global OpenCode MCP config...\x1b[0m');
  mkdirSync(opencodeConfigDir, { recursive: true });

  let opencodeConfig = {};
  if (existsSync(opencodeConfigPath)) {
    try {
      opencodeConfig = JSON.parse(readFileSync(opencodeConfigPath, 'utf-8'));
    } catch {}
  }

  const trelloPath = resolve(globalDir, 'dist', 'mcp-server.js').replace(/\\/g, '/');
  const kaedePath = resolve(globalDir, 'dist', 'kaede-mcp-server.js').replace(/\\/g, '/');
  opencodeConfig.mcp = opencodeConfig.mcp || {};

  if (!opencodeConfig.mcp.trello) {
    opencodeConfig.mcp.trello = {
      type: 'local',
      command: ['bun', trelloPath],
      enabled: true,
      timeout: 30000,
    };
  }

  if (!opencodeConfig.mcp.kaede) {
    opencodeConfig.mcp.kaede = {
      type: 'local',
      command: ['bun', kaedePath],
      enabled: true,
      timeout: 60000,
    };
  }

  writeFileSync(opencodeConfigPath, JSON.stringify(opencodeConfig, null, 2) + '\n', 'utf-8');
  console.log('  \x1b[32m  ✓ MCP trello & kaede added to global OpenCode config\x1b[0m');

  // 5. Setup credentials directory
  mkdirSync(kaedeConfigDir, { recursive: true });

  console.log('');
  console.log('  \x1b[32m  ✅  KAEDE installed globally!\x1b[0m');
  console.log('');
  console.log('  \x1b[90m     Usage:\x1b[0m');
  console.log('  \x1b[90m       \x1b[36mkaede setup\x1b[0m          — setup Trello API key & token');
  console.log('  \x1b[90m       \x1b[36mkaede init\x1b[0m <dir>     — init project with KAEDE');
  console.log('  \x1b[90m       \x1b[36mkaede today\x1b[0m          — show today\'s Trello tasks');
  console.log('  \x1b[90m       \x1b[36mkaede status --mcp\x1b[0m   — check MCP connection');
  console.log('  \x1b[90m       \x1b[36mkaede run\x1b[0m "intent"   — execute intent from playbook');
  console.log('');
  console.log('  \x1b[90m     Two MCP servers registered globally in\x1b[0m');
  console.log('  \x1b[90m     ~/.config/opencode/opencode.json:\x1b[0m');
  console.log('  \x1b[90m       \x1b[36mmcp.trello\x1b[0m    — 24 raw Trello tools\x1b[0m');
  console.log('  \x1b[90m       \x1b[36mmcp.kaede\x1b[0m     — 4 orchestration tools\x1b[0m');
  console.log('');
}

async function cmdStart() {
  const { startApiServer } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'api-server.mjs')).href);
  const server = await startApiServer(parseInt(process.argv[3], 10) || 3456);

  process.on('SIGINT', () => {
    console.log('\n  \x1b[33m  Shutting down API server...\x1b[0m');
    server.close();
    process.exit(0);
  });
  process.on('SIGTERM', () => {
    server.close();
    process.exit(0);
  });
}

async function cmdTestTools() {
  const secrets = getSecrets();
  if (!secrets.TRELLO_API_KEY || !secrets.TRELLO_TOKEN) {
    console.error('  \x1b[31m  ✗ Trello credentials not found.\x1b[0m');
    console.error('  \x1b[33m  Run `node scripts/kaede.mjs setup` first.\x1b[0m');
    return;
  }

  const { TrelloMCPClient } = await import(pathToFileURL(resolve(KAEDE_DIR, 'src', 'trello-client.js')).href);

  console.log('');
  console.log('  \x1b[35m╔══════════════════════════════════════╗\x1b[0m');
  console.log('  \x1b[35m║     KAEDE — Test MCP Tools           ║\x1b[0m');
  console.log('  \x1b[35m╚══════════════════════════════════════╝\x1b[0m');
  console.log('');

  const tools = [
    ['list_workspaces', {}],
    ['list_boards', {}],
    ['get_my_cards', {}],
  ];

  const client = new TrelloMCPClient();
  try {
    const timeout = setTimeout(() => { throw new Error('Connection timed out (30s)'); }, 30000);
    await client.connect();
    clearTimeout(timeout);
    console.log(`  \x1b[32m  ✓ Connected to MCP Server\x1b[0m`);
    console.log('');

    let passed = 0;
    let failed = 0;

    for (const [tool, params] of tools) {
      try {
        const result = await client.callTool(tool, params);
        const summary = Object.keys(result).slice(0, 3).map(k => `${k}: ${Array.isArray(result[k]) ? result[k].length : typeof result[k]}`).join(', ');
        console.log(`  \x1b[32m  ✓ ${tool}\x1b[0m \x1b[90m(${summary})\x1b[0m`);
        passed++;
      } catch (err) {
        console.log(`  \x1b[31m  ✗ ${tool}\x1b[0m \x1b[90m— ${err.message.slice(0, 80)}\x1b[0m`);
        failed++;
      }
    }

    console.log('');
    console.log(`  \x1b[36m  Result: ${passed} passed, ${failed} failed\x1b[0m`);
    if (passed === tools.length) {
      console.log('  \x1b[32m  ✅  All MCP tools responding.\x1b[0m');
    }
  } catch (err) {
    console.error(`  \x1b[31m  ✗ ${err.message}\x1b[0m`);
  } finally {
    client.close();
  }
  console.log('');
}

function cmdHelp() {
  console.log('');
  console.log('  \x1b[35mKAEDE — Koneksi Automated Environment DE\x1b[0m');
  console.log('  \x1b[90mCLI tool untuk manajemen Trello & AI Agent\x1b[0m');
  console.log('');
  console.log('  \x1b[37mUsage:\x1b[0m');
  console.log('    node scripts/kaede.mjs \x1b[36m<command>\x1b[0m');
  console.log('');
  console.log('  \x1b[37mCommands:\x1b[0m');
  console.log('    \x1b[36msetup\x1b[0m     \x1b[90mKonfigurasi Trello API Key & Token\x1b[0m');
  console.log('    \x1b[36mtoday\x1b[0m     \x1b[90mTampilkan task Trello hari ini\x1b[0m');
  console.log('    \x1b[36minit\x1b[0m      \x1b[90mInit KAEDE di project. Flags: --playbook <path>, --tech <stack>, --db <type>\x1b[0m');
  console.log('    \x1b[36mpush\x1b[0m      \x1b[90mBuat Trello cards dari file markdown\x1b[0m');
  console.log('    \x1b[36menv\x1b[0m       \x1b[90mExport credentials ke shell environment\x1b[0m');
  console.log('    \x1b[36mstatus\x1b[0m    \x1b[90mCek status konfigurasi KAEDE (--mcp untuk test koneksi)\x1b[0m');
  console.log('    \x1b[36mplaybook\x1b[0m  \x1b[90mParse/show playbook (parse <path> | show <path>)\x1b[0m');
  console.log('    \x1b[36morchestrate\x1b[0m \x1b[90mLoad context (--playbook <path> [--detail])\x1b[0m');
  console.log('    \x1b[36mrun\x1b[0m       \x1b[90mExecute intent (--playbook <path> [--board <id>] [--dry-run] "intent")\x1b[0m');
  console.log('    \x1b[36mbuild\x1b[0m     \x1b[90mBuild MCP server (dist/mcp-server.js)\x1b[0m');
    console.log('    \x1b[36mstart\x1b[0m     \x1b[90mStart API server (HTTP bridge for frontend) [port]\x1b[0m');
    console.log('    \x1b[36mtest-tools\x1b[0m \x1b[90mUji koneksi 22 MCP tools (butuh Trello credentials)\x1b[0m');
    console.log('    \x1b[36minstall\x1b[0m   \x1b[90mInstall KAEDE globally via npm link\x1b[0m');
    console.log('    \x1b[36mhelp\x1b[0m      \x1b[90mTampilkan pesan ini\x1b[0m');
    console.log('');
    console.log('  \x1b[37mExamples:\x1b[0m');
    console.log('    node scripts/kaede.mjs init                              # interactive');
    console.log('    node scripts/kaede.mjs init ../project --tech Laravel --db MySQL');
    console.log('    node scripts/kaede.mjs init . --playbook playbook.md    # init + playbook ref');
  console.log('    node scripts/kaede.mjs push tasks.md                     # file mode');
  console.log('    node scripts/kaede.mjs push tasks.md --board "My Board" --list "To Do"');
  console.log('    node scripts/kaede.mjs setup');
  console.log('    node scripts/kaede.mjs today');
  console.log('    node scripts/kaede.mjs env | iex                 # Windows PowerShell');
  console.log('    node scripts/kaede.mjs playbook parse ../playbook/sprint.md');
  console.log('    node scripts/kaede.mjs orchestrate --playbook ../playbook/sprint.md --detail');
  console.log('    node scripts/kaede.mjs run --playbook playbook/sprint.md -n "Mulai Sprint Alpha"');
  console.log('    node scripts/kaede.mjs run --playbook playbook/sprint.md --board abc123 "Mulai Sprint Alpha"');
  console.log('    node scripts/kaede.mjs status --mcp');
    console.log('    node scripts/kaede.mjs build');
    console.log('    node scripts/kaede.mjs start');
    console.log('    node scripts/kaede.mjs start 8080');
    console.log('    node scripts/kaede.mjs test-tools');
    console.log('    node scripts/kaede.mjs install');
    console.log('');
    console.log('  \x1b[37mEnv:\x1b[0m');
    console.log('    \x1b[36mKAEDE_DIR\x1b[0m   \x1b[90mOverride path ke instalasi KAEDE (default: auto-detect)\x1b[0m');
    console.log('');
}

// ─── Main ───

async function main() {
  const cmd = process.argv[2] || 'help';

  switch (cmd) {
    case 'setup':
      await cmdSetup();
      break;
    case 'today':
      await cmdToday();
      break;
    case 'init':
      await cmdInit();
      break;
    case 'push':
      await cmdPush();
      break;
    case 'env':
      await cmdEnv();
      break;
    case 'status':
      await cmdStatus();
      break;
    case 'playbook':
      await cmdPlaybook();
      break;
    case 'orchestrate':
      await cmdOrchestrate();
      break;
    case 'run':
      await cmdRun();
      break;
    case 'build':
      await cmdBuild();
      break;
    case 'install':
      await cmdInstall();
      break;
    case 'start':
      await cmdStart();
      break;
    case 'test-tools':
      await cmdTestTools();
      break;
    case 'help':
    case '--help':
    case '-h':
      cmdHelp();
      break;
    default:
      console.error(`  \x1b[31m  Unknown command: ${cmd}\x1b[0m`);
      cmdHelp();
  }
}

main().catch((err) => {
  console.error('  \x1b[31m  Error:\x1b[0m', err.message);
});
